# Community Music School -- the room's FEATURES, built into the CMS Classroom shell.
# Loaded by room.rb (WR_CMS.run!). EVERY POSITION HERE IS ESTIMATED FROM THE TWO CLIENT
# PHOTOS, NOT FIELD MEASURED. Positions come from ray-casting / two-photo triangulation
# with the joint7 camera fit (.forge/builder/cms/fit/rc.py, joint7.json, scale_joint7.json);
# the gridded crops they were read from are regenerated by fit/crop.py.
#
# Frame (inches): X west->east (Wall C at 0, Wall A at W), Y south->north (Wall B at 0,
# Wall D at L), Z up.  Wall 1 = N = D, 2 = E = A, 3 = S = B, 4 = W = C.
#
# Naming follows wr-scene-walls PIECE_RE so a hidden wall takes its fittings with it:
#   "Wall <n> lower|stripe|upper"  wall bands (built around the openings)
#   "Wall <n> fittings"            everything mounted on wall n
#   "Door leaf <n> ..."            the two door leaves
#   "Ceiling fixtures"             light fittings + smoke detector (tag WR-Ceiling)
module WR_CMS
  TEX = File.join(DIR, 'tex').freeze unless const_defined?(:TEX)
  STRIPE_H = 1.25 unless const_defined?(:STRIPE_H)

  # ---- openings (u along the wall, z range, depth into the wall; nil = through) ----
  # Wall 2 windows: Y from photo-B casts onto the wall plane (w1 179.0-234.5; w2 B 38.3-97.6,
  # A 37.5-92.1 -> 38-95); head Z 103-106 -> 105.5; sill 34 (B casts 31.4-35.9).
  WIN = [
    { key: 'w1', y0: 179.0, y1: 234.5, sill: 34.0, head: 105.5, tex: 'backdrop-w1.jpg' },
    { key: 'w2', y0: 38.0,  y1: 95.0,  sill: 34.0, head: 105.5, tex: 'backdrop-w2.jpg' }
  ].freeze
  REVEAL   = 16.0
  # wall face -> glass (triangulated 11-16 in on window 2; photo B's side reveal
                    # on window 1 reads ~2x wider than a 12 in reveal renders)
  EAST_T   = 20.0   # exterior masonry wall, deep enough for the reveal + frame
  NICHE_D  = 4.0    # radiator niche below each stool (photo B: niche face sits behind the pier)
  APRON_BOT = 28.25
  CLOSET = { x0: 144.2, x1: 175.9, head: 86.3, cas: 4.5 }.freeze          # photo A casts, B agrees <2 in
  ENTRY  = { y0: 85.5, y1: 123.0, head: 104.0, door_head: 85.0, cas: 5.0 } # photo A casts
  PIL    = { y0: 134.0, y1: 155.0, d: 7.0 }.freeze                        # photo B floor casts

  def self.thick(n)
    n == 2 ? EAST_T : T
  end

  def self.openings(n)
    l, w, h, = dims
    case n
    when 2
      WIN.flat_map do |wi|
        [{ u0: wi[:y0], u1: wi[:y1], z0: wi[:sill] - 0.75, z1: wi[:head], d: nil },
         { u0: wi[:y0], u1: wi[:y1], z0: -1.0, z1: APRON_BOT, d: NICHE_D }]
      end
    when 3 then [{ u0: CLOSET[:x0], u1: CLOSET[:x1], z0: -1.0, z1: CLOSET[:head], d: nil }]
    when 4 then [{ u0: ENTRY[:y0], u1: ENTRY[:y1], z0: -1.0, z1: ENTRY[:head], d: nil }]
    else []
    end
  end

  # A slab of wall n between u=a..b, z0..z1, from depth d0 to d1 behind the interior face.
  def self.wall_box(ents, n, a, b, z0, z1, d0, d1, m, name = nil)
    l, w, = dims
    case n
    when 1 then box(ents, a, l + d0, z0, b, l + d1, z1, m, name)
    when 2 then box(ents, w + d0, a, z0, w + d1, b, z1, m, name)
    when 3 then box(ents, a, -d1, z0, b, -d0, z1, m, name)
    when 4 then box(ents, -d1, a, z0, -d0, b, z1, m, name)
    end
  end

  def self.run_of(n)
    l, w, = dims
    [1, 3].include?(n) ? [-thick(4), w + thick(2)] : [0.0, l]
  end

  # Replaces the plain prisms: each band of each wall, cut around that wall's openings.
  def self.walls_with_openings!(we)
    l, w, h, zc = dims
    bands = [[0.0, zc - STRIPE_H / 2, :lower, 'lower'], [zc - STRIPE_H / 2, zc + STRIPE_H / 2, :stripe, 'stripe'],
             [zc + STRIPE_H / 2, h, :upper, 'upper']]
    (1..4).each do |n|
      ops = openings(n)
      r0, r1 = run_of(n)
      t = thick(n)
      bands.each do |bz0, bz1, mk, nm|
        g = we.add_group
        g.name = "Wall #{n} #{nm}"
        us = ([r0, r1] + ops.flat_map { |o| [o[:u0], o[:u1]] }).map { |u| u.clamp(r0, r1) }.uniq.sort
        us.each_cons(2) do |a, b|
          next if b - a < 0.01
          um = (a + b) / 2
          act = ops.select { |o| o[:u0] < um && um < o[:u1] }
          zs = ([bz0, bz1] + act.flat_map { |o| [o[:z0], o[:z1]] }).map { |z| z.clamp(bz0, bz1) }.uniq.sort
          zs.each_cons(2) do |za, zb|
            next if zb - za < 0.01
            zm = (za + zb) / 2
            cov = act.select { |o| o[:z0] < zm && zm < o[:z1] }
            next if cov.any? { |o| o[:d].nil? }
            d = cov.map { |o| o[:d] }.max || 0.0
            wall_box(g.entities, n, a, b, za, zb, d, t, @m[mk])
          end
        end
      end
    end
    # pilaster between the windows, banded like the wall (Wall piece: hides with Wall 2)
    pg = we.add_group
    pg.name = 'Wall 2 pilaster'
    bands.each { |bz0, bz1, mk, _| box(pg.entities, w - PIL[:d], PIL[:y0], bz0, w, PIL[:y1], bz1, @m[mk]) }
  end

  # ------------------------------------------------------------- materials --
  def self.feature_materials!
    @m[:carpet]  = pbr('CMS Carpet', [96, 104, 120], 0.95)
    @m[:carpet].texture = File.join(TEX, 'carpet-fleck.png')
    @m[:carpet].texture.size = 18.0
    # photo hue, lifted to a plausible reflectance (see notes.md: colours are estimates)
    @m[:upper]   = pbr('CMS Wall Cream', [230, 219, 190], 0.85)
    @m[:lower]   = pbr('CMS Wall Tan', [210, 180, 140], 0.85)
    @m[:stripe]  = pbr('CMS Stripe Teal', [42, 66, 64], 0.6)
    @m[:ceiling] = pbr('CMS Ceiling', [228, 223, 210], 0.9)
    @m[:oak]     = pbr('CMS Oak', [165, 112, 62], 0.45)
    @m[:reveal]  = pbr('CMS Reveal White', [234, 230, 214], 0.8)
    @m[:steel]   = pbr('CMS Steel Window Green-Gray', [52, 62, 56], 0.5, 0.3)
    @m[:glass]   = pbr('CMS Glass', [205, 215, 215], 0.05)
    @m[:glass].alpha = 0.12
    @m[:frost]   = pbr('CMS Frosted Glass', [218, 224, 222], 0.3)
    @m[:frost].alpha = 0.7
    @m[:rad]     = pbr('CMS Radiator Cream', [208, 199, 175], 0.55, 0.2)
    @m[:pipe]    = pbr('CMS Pipe Cream', [214, 206, 184], 0.5)
    @m[:pvc]     = pbr('CMS PVC White', [236, 236, 231], 0.4)
    @m[:white]   = pbr('CMS Whiteboard', [232, 231, 226], 0.15)
    @m[:tack]    = pbr('CMS Tackboard', [196, 181, 153], 0.95)
    @m[:plate]   = pbr('CMS Device Ivory', [234, 227, 208], 0.4)
    @m[:shelf]   = pbr('CMS Shelf White', [226, 223, 214], 0.6)
    @m[:closet]  = pbr('CMS Closet Wall', [222, 216, 198], 0.85)
    @m[:vct]     = pbr('CMS Hall Floor', [160, 158, 150], 0.5)
    @m[:hall]    = pbr('CMS Hall Wall', [196, 186, 164], 0.85)
    @m[:metal]   = pbr('CMS Fixture White Metal', [238, 238, 233], 0.35)
    @m[:lens]    = pbr('CMS Fixture Lens', [246, 246, 240], 0.2)
    @m[:louver]  = pbr('CMS Fixture Louver', [214, 214, 208], 0.25, 0.6)
    @m[:alu]     = pbr('CMS Aluminum Strip', [182, 184, 186], 0.35, 0.8)
    @m[:black]   = pbr('CMS Clip Black', [30, 30, 30], 0.4)
    @m[:brass]   = pbr('CMS Knob Brass', [168, 138, 80], 0.3, 0.9)
    @m[:plaque]  = pbr('CMS Plaque White', [240, 236, 228], 0.6)
    WIN.each do |wi|
      mm = model.materials["CMS Backdrop #{wi[:key]}"] || model.materials.add("CMS Backdrop #{wi[:key]}")
      mm.texture = File.join(TEX, wi[:tex])
      @m[:"bd_#{wi[:key]}"] = mm
    end
  end

  # ----------------------------------------------------------------- helpers --
  def self.grp(ents, name, tag = nil)
    g = ents.add_group
    g.name = name
    g.layer = layer(tag) if tag
    g
  end

  # vertical cylinder
  def self.cyl(ents, cx, cy, z0, z1, dia, m, seg = 16)
    g = ents.add_group
    c = g.entities.add_circle([cx, cy, z0], [0, 0, 1], dia / 2.0, seg)
    f = g.entities.add_face(c)
    f.reverse! if f.normal.z < 0
    f.pushpull(z1 - z0)
    g.material = m
    g
  end

  # a flat face (pts), given material both sides
  def self.flat(ents, pts, m)
    f = ents.add_face(pts)
    f.material = m
    f.back_material = m
    f
  end

  # rectangular device plate on a wall face. n = wall, (u, z) centre, bw along wall, bh tall,
  # proud of the face by `off` (for baseboard or pilaster mounts).
  def self.plate(ents, n, u, z, bw, bh, off = 0.0)
    l, w, = dims
    t = 0.22
    case n
    when 1 then box(ents, u - bw / 2, l - off - t, z - bh / 2, u + bw / 2, l - off, z + bh / 2, @m[:plate])
    when 2 then box(ents, w - off - t, u - bw / 2, z - bh / 2, w - off, u + bw / 2, z + bh / 2, @m[:plate])
    when 3 then box(ents, u - bw / 2, off, z - bh / 2, u + bw / 2, off + t, z + bh / 2, @m[:plate])
    when 4 then box(ents, off, u - bw / 2, z - bh / 2, off + t, u + bw / 2, z + bh / 2, @m[:plate])
    end
  end

  # ------------------------------------------------------------- baseboards --
  # [x0,y0,x1,y1, inward normal [nx,ny]] -- the face line; board 0.75 thick to 6.4, cap 1.0 to 7.2
  # (photo A: baseboard top 7.1 in on Wall B).
  def self.baseboard(ents, x0, y0, x1, y1, nrm)
    nx, ny = nrm
    [[0.0, 6.4, 0.75], [6.4, 7.2, 1.0]].each do |z0, z1, t|
      if ny != 0
        box(ents, x0, y0, z0, x1, y0 + ny * t, z1, @m[:oak])
      else
        box(ents, x0, y0, z0, x0 + nx * t, y1, z1, @m[:oak])
      end
    end
  end

  # ---------------------------------------------------------------- walls ----
  def self.wall1_fittings!(e)
    l, w, h, zc = dims
    g = grp(e, 'Wall 1 fittings')
    ge = g.entities
    baseboard(ge, 0, l, w, l, [0, -1])
    # tack strip + clips (photo B left edge: strip X 90..167 cast on Wall D, just above the stripe;
    # its west end is out of frame -- 60 is assumed)
    box(ge, 60.0, l - 0.35, zc + 0.7, 167.0, l, zc + 2.3, @m[:alu], 'tack strip')
    [89.0, 122.0, 150.0].each { |x| box(ge, x - 0.9, l - 0.95, zc - 1.8, x + 0.9, l - 0.35, zc + 1.6, @m[:black]) }
  end

  def self.wall2_fittings!(e)
    l, w, h, zc = dims
    g = grp(e, 'Wall 2 fittings')
    ge = g.entities
    # baseboards: runs, niche backs + returns, round the pilaster
    y_runs = [[0.0, 38.0], [95.0, PIL[:y0]], [PIL[:y1], 179.0], [234.5, l]]
    y_runs.each { |a, b| baseboard(ge, w, a, w, b, [-1, 0]) }
    WIN.each do |wi|
      baseboard(ge, w + NICHE_D, wi[:y0], w + NICHE_D, wi[:y1], [-1, 0])
      box(ge, w, wi[:y0], 0, w + NICHE_D, wi[:y0] + 0.75, 6.4, @m[:oak])
      box(ge, w, wi[:y1] - 0.75, 0, w + NICHE_D, wi[:y1], 6.4, @m[:oak])
    end
    pf = w - PIL[:d]
    baseboard(ge, pf, PIL[:y0], pf, PIL[:y1], [-1, 0])
    box(ge, pf - 0.75, PIL[:y0] - 0.75, 0, w, PIL[:y0], 6.4, @m[:oak])
    box(ge, pf - 0.75, PIL[:y1], 0, w, PIL[:y1] + 0.75, 6.4, @m[:oak])

    WIN.each { |wi| window!(ge, wi) }

    # radiators (photo B casts on the radiator front plane; w2 also triangulated):
    # rad 1 Y 190-228 (38 in), top 26.5; rad 2 Y 43.5-80.5 (37 in), top 25.0
    # rad 2 RE-SEATED 22 Sep, twice, on Benton's word ("too far left" in the photos). Second pass
    # measured RELATIONSHIPS to its niche on the wall planes, not pixel error:
    #   photo B: niche jambs 39.3 / 97.6, radiator front 58.7-95.4 -> centre 8.5 in N of the niche
    #            centre, N end 2.2 in inside the N jamb, S end 19.4 in off the S jamb;
    #   photo A (grazing, weaker along the wall): jambs 44.2 / 94.3, radiator 56.8-94.9 -> 6.6 in N,
    #            N end 0.6 in proud of the jamb, S end 12.6 in off it.
    # Both put it ~37 in long (not 40) and inset from the N jamb (the 55-95 seat was flush with it,
    # which is what read as "too far left"). Seated at the mean: 7.5 in N of the niche centre, N end
    # 2.5 in inside the jamb. The niche (38-95) sits between the two photos' jambs and is NOT moved.
    radiator!(ge, 190.0, 228.0, 26.5)
    # BENTON'S RULING, 22 Sep: shift radiator 2 about 1 ft to the RIGHT as seen facing the window wall
    # (photo B's view) = 12 in SOUTH, 55.5-92.5 -> 43.5-80.5, length kept at 37 in. This OVERRIDES the
    # photo measurement above. S end 5.5 in clear of the S niche jamb (38); riser at Y 83.1, in the niche.
    radiator!(ge, 43.5, 80.5, 25.0)

    # pilaster outlet (photo B cast on the pilaster face; photo A triangulation agrees on Y)
    plate(ge, 2, 145.5, 17.3, 2.75, 4.5, PIL[:d])

    # rainbow plaque on the chair rail (photo B: Y 249.5-256.6, Z 57.9-63)
    rb = grp(ge, 'rainbow plaque')
    re = rb.entities
    box(re, w - 0.3, 249.5, 57.9, w, 256.6, 59.7, @m[:plaque])
    cy, cz = 253.05, 59.7
    [[3.2, 2.6, [176, 72, 56]], [2.6, 2.0, [206, 128, 64]], [2.0, 1.4, [196, 168, 112]], [1.4, 0.9, [120, 150, 160]]].each_with_index do |(ro, ri, rgb), i|
      mat = pbr("CMS Rainbow #{i}", rgb, 0.6)
      seg = 16
      pts = (0..seg).map { |k| a = Math::PI * k / seg; [w - 0.32, cy + ro * Math.cos(a), cz + ro * Math.sin(a)] } +
            (0..seg).map { |k| a = Math::PI * (seg - k) / seg; [w - 0.32, cy + ri * Math.cos(a), cz + ri * Math.sin(a)] }
      flat(re, pts, mat)
    end

    decals!(ge)
  end

  def self.window!(ge, wi)
    l, w, h, = dims
    y0, y1, s, hd = wi[:y0], wi[:y1], wi[:sill], wi[:head]
    g = grp(ge, "window #{wi[:key]}")
    e = g.entities
    gx = w + REVEAL
    # white reveal linings (jambs, head, sill board)
    box(e, w, y0, s - 0.75, gx + 0.5, y0 + 0.12, hd, @m[:reveal])
    box(e, w, y1 - 0.12, s - 0.75, gx + 0.5, y1, hd, @m[:reveal])
    box(e, w, y0, hd - 0.12, gx + 0.5, y1, hd, @m[:reveal])
    box(e, w, y0, s - 0.75, gx + 0.5, y1, s, @m[:reveal])
    # oak stool + apron at the face
    box(e, w - 1.75, y0 - 3.0, s - 1.25, w, y1 + 3.0, s, @m[:oak])
    box(e, w - 0.75, y0 - 1.5, APRON_BOT, w, y1 + 1.5, s - 1.25, @m[:oak])
    # steel window: 2 in frame, 6 x 6 lights, heavier centre mullion (counted on photo B, window 1;
    # window 2's north third is hidden behind its reveal in both photos -- assumed the same 6 x 6)
    fr = 2.0
    ya, yb, za, zb = y0 + 0.12, y1 - 0.12, s, hd - 0.12
    box(e, gx, ya, za, gx + 1.75, ya + fr, zb, @m[:steel])
    box(e, gx, yb - fr, za, gx + 1.75, yb, zb, @m[:steel])
    box(e, gx, ya, za, gx + 1.75, yb, za + fr, @m[:steel])
    box(e, gx, ya, zb - fr, gx + 1.75, yb, zb, @m[:steel])
    iy0, iy1, iz0, iz1 = ya + fr, yb - fr, za + fr, zb - fr
    (1..5).each do |i|
      yy = iy0 + (iy1 - iy0) * i / 6.0
      bw = i == 3 ? 2.2 : 0.9
      box(e, gx + 0.25, yy - bw / 2, iz0, gx + 1.5, yy + bw / 2, iz1, @m[:steel])
      zz = iz0 + (iz1 - iz0) * i / 6.0
      box(e, gx + 0.25, iy0, zz - 0.45, gx + 1.5, iy1, zz + 0.45, @m[:steel])
    end
    # operable vent: the two centre columns, rows 2-5, outlined by a heavier sash bar
    vy0 = iy0 + (iy1 - iy0) * 2 / 6.0
    vy1 = iy0 + (iy1 - iy0) * 4 / 6.0
    vz0 = iz0 + (iz1 - iz0) * 1 / 6.0
    vz1 = iz0 + (iz1 - iz0) * 5 / 6.0
    [[vy0 - 0.7, vy0 + 0.7, vz0, vz1], [vy1 - 0.7, vy1 + 0.7, vz0, vz1]].each { |p, q, r, t| box(e, gx - 0.3, p, r, gx + 0.25, q, t, @m[:steel]) }
    [[vz0 - 0.7, vz0 + 0.7], [vz1 - 0.7, vz1 + 0.7]].each { |r, t| box(e, gx - 0.3, vy0 - 0.7, r, gx + 0.25, vy1 + 0.7, t, @m[:steel]) }
    ym = (iy0 + iy1) / 2
    lz = iz0 + (iz1 - iz0) * 0.55
    box(e, gx - 1.2, ym - 0.6, lz - 1.6, gx - 0.3, ym + 0.6, lz + 1.6, @m[:steel], 'sash lock')
    # glass
    flat(e, [[gx + 1.0, iy0, iz0], [gx + 1.0, iy1, iz0], [gx + 1.0, iy1, iz1], [gx + 1.0, iy0, iz1]], @m[:glass])
    # backdrop: photo B's view through this window (mullions inpainted), on a plane outside.
    # u runs south (-Y) as seen from inside looking east.
    bx = w + thick(2) + 6.0   # close behind the wall: keeps it out of the plan's dimension rows
    mg = 14.0
    bd = e.add_face([bx, y1 + mg, s - mg], [bx, y0 - mg, s - mg], [bx, y0 - mg, hd + mg], [bx, y1 + mg, hd + mg])
    bd.reverse! if bd.normal.x > 0
    mat = @m[:"bd_#{wi[:key]}"]
    pts = [Geom::Point3d.new(bx, iy1, iz0), [0, 0], Geom::Point3d.new(bx, iy0, iz0), [1, 0],
           Geom::Point3d.new(bx, iy0, iz1), [1, 1], Geom::Point3d.new(bx, iy1, iz1), [0, 1]]
    bd.position_material(mat, pts, true)
    bd.back_material = mat
  end

  def self.radiator!(ge, ya, yb, top)
    l, w, = dims
    g = grp(ge, "radiator #{ya.round}-#{yb.round}")
    e = g.entities
    x0, x1 = w - 5.0, w + 2.0
    n = ((yb - ya) / 2.5).floor
    step = (yb - ya) / n
    n.times do |i|
      s = ya + i * step
      lo = (i == 0 || i == n - 1) ? 0.0 : 3.5
      box(e, x0, s + 0.25, lo, x1, s + step - 0.35, top - 0.6, @m[:rad])
      box(e, x0 + 0.8, s + 0.25, top - 0.6, x1 - 0.8, s + step - 0.35, top, @m[:rad])
    end
    box(e, x0 + 2.0, ya, 4.2, x1 - 2.0, yb, 5.8, @m[:rad])
    box(e, x0 + 2.0, ya, top - 3.0, x1 - 2.0, yb, top - 1.4, @m[:rad])
    # supply at the north end: riser from the floor, valve, stub into the radiator
    py = yb + 2.6
    cyl(e, w - 1.5, py, 0.0, top - 4.0, 1.3, @m[:pipe])
    cyl(e, w - 1.5, py, top - 6.5, top - 3.5, 2.4, @m[:pipe])
    box(e, w - 2.2, yb - 0.2, top - 5.6, w - 0.8, py, top - 4.2, @m[:pipe])
  end

  def self.decals!(ge)
    l, w, = dims
    f = File.join(DIR, 'fit', 'decals_joint7.json')
    return unless File.exist?(f)
    g = grp(ge, 'paint-splatter decals')
    e = g.entities
    JSON.parse(File.read(f)).each_with_index do |d, i|
      y, z = d['Y'].to_f, d['Z'].to_f
      next if y.between?(248.0, 258.0) && z.between?(56.0, 64.5) # the rainbow plaque, not a splat
      x = (d['on'] == 'pil' ? w - PIL[:d] : w) - 0.06
      rgb = d['rgb'].map { |c| [(c * 1.3).round, 255].min }
      mat = pbr("CMS Decal #{rgb.join('-')}", rgb, 0.5)
      r = [d['d'].to_f / 2.0, 0.5].max
      rng = Random.new(1000 + i)
      k = 22
      ph = Array.new(3) { rng.rand(0.0..2 * Math::PI) }
      am = [rng.rand(0.10..0.18), rng.rand(0.06..0.12), rng.rand(0.04..0.08)]
      pts = (0...k).map do |j|
        a = 2 * Math::PI * j / k
        rr = r * (1.0 + am[0] * Math.sin(3 * a + ph[0]) + am[1] * Math.sin(5 * a + ph[1]) + am[2] * Math.sin(7 * a + ph[2]))
        rr *= 1.35 if j % 7 == 3   # a short drip arm
        [x, y + rr * Math.cos(a), z + rr * Math.sin(a)]
      end
      flat(e, pts, mat)
      rng.rand(3..5).times do
        a = rng.rand(0.0..2 * Math::PI)
        dd = r * rng.rand(1.25..1.9)
        rr = r * rng.rand(0.1..0.2)
        cy, cz = y + dd * Math.cos(a), z + dd * Math.sin(a)
        flat(e, (0...10).map { |j| b = 2 * Math::PI * j / 10; [x, cy + rr * Math.cos(b), cz + rr * Math.sin(b)] }, mat)
      end
    end
  end

  def self.wall3_fittings!(e)
    l, w, h, zc = dims
    g = grp(e, 'Wall 3 fittings')
    ge = g.entities
    c = CLOSET
    ox0, ox1 = c[:x0] - c[:cas], c[:x1] + c[:cas]
    baseboard(ge, 0, 0, ox0, 0, [0, 1])
    baseboard(ge, ox1, 0, w, 0, [0, 1])
    # closet casing + jamb lining (oak)
    box(ge, ox0, 0, 0, c[:x0], 0.9, c[:head] + 5.4, @m[:oak])
    box(ge, c[:x1], 0, 0, ox1, 0.9, c[:head] + 5.4, @m[:oak])
    box(ge, ox0, 0, c[:head], ox1, 0.9, c[:head] + 5.4, @m[:oak])
    box(ge, c[:x0], -thick(3), 0, c[:x0] + 0.7, 0, c[:head], @m[:oak])
    box(ge, c[:x1] - 0.7, -thick(3), 0, c[:x1], 0, c[:head], @m[:oak])
    box(ge, c[:x0], -thick(3), c[:head] - 0.7, c[:x1], 0, c[:head], @m[:oak])
    # closet interior (depth ~26 in assumed): floor, walls, white shelving west, PVC stack east
    cl = grp(ge, 'closet interior')
    ce = cl.entities
    y4 = -thick(3)
    box(ce, 139.0, -31.0, -0.5, 182.0, y4, 0.0, @m[:vct])
    box(ce, 139.0, -32.0, 0, 182.0, -31.0, 97.0, @m[:closet])
    box(ce, 138.0, -32.0, 0, 139.0, y4, 97.0, @m[:closet])
    box(ce, 182.0, -32.0, 0, 183.0, y4, 97.0, @m[:closet])
    box(ce, 138.0, -32.0, 96.0, 183.0, y4, 97.0, @m[:closet])
    [16, 26, 36, 46, 56, 66, 76].each { |z| box(ce, 139.0, -31.0, z - 0.75, 168.0, -13.0, z, @m[:shelf]) }
    [[173.0, -26.0], [177.5, -21.0]].each do |px, py|
      cyl(ce, px, py, 0, 70.0, 3.3, @m[:pvc])
      [18, 38, 58].each { |z| cyl(ce, px, py, z, z + 2.2, 4.3, @m[:pvc]) }
    end
    # open closet door: hinged on the east jamb, standing square to Wall B (photo A + B)
    dl = grp(ge, 'Door leaf 3 closet')
    de = dl.entities
    lx0, lx1 = c[:x1] - 1.75 - 0.7, c[:x1] - 0.7
    ly1 = 0.2 + (c[:x1] - c[:x0] - 1.4)
    box(de, lx0, 0.2, 0.5, lx1, ly1, c[:head] - 0.8, @m[:oak])
    [[8.0, 38.0], [44.0, 80.0]].each do |pz0, pz1|
      [lx0 - 0.25, lx1].each { |fx| box(de, fx, 4.5, pz0, fx + 0.25, ly1 - 4.5, pz1, @m[:oak]) }
    end
    [lx0 - 1.6, lx1].each { |fx| box(de, fx, ly1 - 3.2, 35.0, fx + 1.6, ly1 - 1.8, 36.4, @m[:brass]) }
    # whiteboard (photo A casts, B agrees): frame X 49.3-134.0, top 79.6, tray top 32.2
    wb = grp(ge, 'whiteboard')
    we = wb.entities
    fx0, fx1, ft, fb = 49.3, 134.0, 79.6, 32.2
    box(we, fx0, 0, ft - 2.75, fx1, 1.25, ft, @m[:oak])
    box(we, fx0, 0, fb, fx0 + 2.75, 1.25, ft, @m[:oak])
    box(we, fx1 - 2.75, 0, fb, fx1, 1.25, ft, @m[:oak])
    [71.5, 112.3].each { |x| box(we, x - 0.75, 0, fb, x + 0.75, 1.25, ft - 2.75, @m[:oak]) }
    box(we, fx0 + 2.75, 0, fb, 70.75, 0.45, ft - 2.75, @m[:tack])
    box(we, 72.25, 0, fb, 111.55, 0.45, ft - 2.75, @m[:white])
    box(we, 113.05, 0, fb, fx1 - 2.75, 0.45, ft - 2.75, @m[:tack])
    box(we, 47.0, 0, fb - 1.0, 136.3, 3.5, fb, @m[:oak])
    box(we, 47.0, 0, 25.4, 136.3, 1.0, fb - 1.0, @m[:oak])
    box(we, 106.0, 1.2, fb, 111.0, 3.0, fb + 1.1, @m[:black], 'eraser')
    # duplex outlet on the baseboard (photo A + B casts X 93.6 / 92.9): landscape
    plate(ge, 3, 93.3, 4.0, 4.5, 2.75, 0.75)
  end

  def self.wall4_fittings!(e)
    l, w, h, zc = dims
    g = grp(e, 'Wall 4 fittings')
    ge = g.entities
    en = ENTRY
    oy0, oy1 = en[:y0] - en[:cas], en[:y1] + en[:cas]
    baseboard(ge, 0, 0, 0, oy0, [1, 0])
    baseboard(ge, 0, oy1, 0, l, [1, 0])
    t = thick(4)
    # heavy oak casing: 5 in legs, 6 in head, projecting cap
    box(ge, 0, oy0, 0, 1.0, en[:y0], en[:head], @m[:oak])
    box(ge, 0, en[:y1], 0, 1.0, oy1, en[:head], @m[:oak])
    box(ge, 0, oy0, en[:head], 1.0, oy1, en[:head] + 5.0, @m[:oak])
    box(ge, 0, oy0 - 0.6, en[:head] + 5.0, 1.7, oy1 + 0.6, en[:head] + 6.6, @m[:oak])
    # jambs, head, threshold
    box(ge, -t, en[:y0], 0, 0, en[:y0] + 0.7, en[:head], @m[:oak])
    box(ge, -t, en[:y1] - 0.7, 0, 0, en[:y1], en[:head], @m[:oak])
    box(ge, -t, en[:y0], en[:head] - 0.7, 0, en[:y1], en[:head], @m[:oak])
    box(ge, -t, en[:y0], 0, 0, en[:y1], 0.4, @m[:oak])
    # transom bar + frosted transom sash (photo A: door head 85, glass top ~102)
    box(ge, -t, en[:y0], en[:door_head], 0, en[:y1], en[:door_head] + 3.5, @m[:oak])
    ty0, ty1, tz0, tz1 = en[:y0] + 0.7, en[:y1] - 0.7, en[:door_head] + 3.5, en[:head] - 0.7
    [[ty0, ty0 + 1.5, tz0, tz1], [ty1 - 1.5, ty1, tz0, tz1]].each { |a, b, c, d| box(ge, -2.9, a, c, -1.1, b, d, @m[:oak]) }
    [[tz0, tz0 + 1.5], [tz1 - 1.5, tz1]].each { |c, d| box(ge, -2.9, ty0, c, -1.1, ty1, d, @m[:oak]) }
    flat(ge, [[-2.0, ty0 + 1.5, tz0 + 1.5], [-2.0, ty1 - 1.5, tz0 + 1.5], [-2.0, ty1 - 1.5, tz1 - 1.5], [-2.0, ty0 + 1.5, tz1 - 1.5]], @m[:frost])
    # door leaf on its south hinge, swung out ~180 deg and lying back against the corridor face of
    # Wall C (photo A shows only a narrow band of it past the far jamb)
    dl = grp(ge, 'Door leaf 4 entry')
    box(dl.entities, -t - 1.75, en[:y0] + 0.7 - (en[:y1] - en[:y0] - 1.4), 0.5, -t, en[:y0] + 0.7, en[:door_head] - 0.5, @m[:oak])
    # corridor beyond (unlit in the photo)
    hl = grp(ge, 'corridor')
    he = hl.entities
    box(he, -110.0, 30.0, -0.5, -t, 180.0, 0.0, @m[:vct])
    box(he, -111.0, 30.0, 0, -110.0, 180.0, 110.0, @m[:hall])
    box(he, -110.0, 29.0, 0, -t, 30.0, 110.0, @m[:hall])
    box(he, -110.0, 180.0, 0, -t, 181.0, 110.0, @m[:hall])
    box(he, -111.0, 29.0, 110.0, -t, 181.0, 111.0, @m[:ceiling])
    # switch plate (photo A: Y 132.3, Z 52.5-55.7) and outlet (Y 132.5, Z 18.7)
    plate(ge, 4, 132.3, 54.0, 2.75, 4.5)
    box(ge, 0.22, 132.0, 53.4, 0.7, 132.6, 54.6, @m[:plate], 'toggle')
    plate(ge, 4, 132.5, 18.7, 2.75, 4.5)
    # white pipe riser with brackets (photo A: Y ~136 cast on the wall; set 2.6 in off it)
    rs = grp(ge, 'pipe riser')
    re = rs.entities
    # (photo A: the switch sits between the casing and the pipe, so the pipe hugs the wall)
    cyl(re, 1.6, 136.8, 0.0, h, 2.0, @m[:pvc])
    [[17.0, 21.0], [h - 4.0, h]].each { |a, b| cyl(re, 1.6, 136.8, a, b, 2.6, @m[:pvc]) }
    [36.0, 76.0, 112.0].each { |z| box(re, 0.0, 135.6, z, 2.8, 138.0, z + 0.6, @m[:pvc]) }
  end

  # --------------------------------------------------------------- ceiling --
  def self.ceiling_fixtures!(root)
    l, w, h, = dims
    g = grp(root.entities, 'Ceiling fixtures', 'WR-Ceiling')
    e = g.entities
    z0 = h - 4.4
    # Run 1 -- lensed wraparounds (photo A + B ties): X 38.5-135.5, Y 68.5-78.5 (the 97 in scale anchor)
    [[38.5, 87.0], [87.0, 135.5]].each do |a, b|
      u = grp(e, 'fixture run 1 wraparound')
      ue = u.entities
      box(ue, a, 68.5, h - 0.85, b, 78.5, h, @m[:metal])
      box(ue, a, 68.5, z0, a + 0.6, 78.5, h - 0.85, @m[:metal])
      box(ue, b - 0.6, 68.5, z0, b, 78.5, h - 0.85, @m[:metal])
      box(ue, a + 0.6, 68.8, z0, b - 0.6, 78.2, h - 0.85, @m[:lens])
    end
    # Run 2 -- surface troffer with a parabolic egg-crate louver (photo B top-left):
    # east end X 138.5, Y 202-212.5, parallel to run 1
    [[41.5, 90.0], [90.0, 138.5]].each do |a, b|
      u = grp(e, 'fixture run 2 louvered')
      ue = u.entities
      y0, y1 = 202.0, 212.5
      box(ue, a, y0, h - 0.85, b, y1, h, @m[:metal])
      box(ue, a, y0, z0, b, y0 + 0.6, h - 0.85, @m[:metal])
      box(ue, a, y1 - 0.6, z0, b, y1, h - 0.85, @m[:metal])
      box(ue, a, y0, z0, a + 0.6, y1, h - 0.85, @m[:metal])
      box(ue, b - 0.6, y0, z0, b, y1, h - 0.85, @m[:metal])
      box(ue, a + 0.6, y0 + 0.6, h - 1.25, b - 0.6, y1 - 0.6, h - 0.85, @m[:lens])
      ym = (y0 + y1) / 2
      box(ue, a + 0.6, ym - 0.15, z0, b - 0.6, ym + 0.15, z0 + 2.2, @m[:louver])
      xs = (1..7).map { |i| a + (b - a) * i / 8.0 }
      xs.each { |x| box(ue, x - 0.15, y0 + 0.6, z0, x + 0.15, y1 - 0.6, z0 + 2.2, @m[:louver]) }
    end
    # smoke detector (photo A + B tie)
    cyl(e, 45.0, 86.6, h - 1.6, h, 5.5, @m[:metal], 24)
  end

  def self.build_features!(root)
    feature_materials!
    root.entities.grep(Sketchup::Group).find { |gg| gg.name == 'Floor' }&.material = @m[:carpet]
    walls = root.entities.grep(Sketchup::Group).find { |gg| gg.name == 'Walls' }
    we = walls.entities
    wall1_fittings!(we)
    wall2_fittings!(we)
    wall3_fittings!(we)
    wall4_fittings!(we)
    ceiling_fixtures!(root)
  end
end
