# @title Assembly close-ups — export (manual insets)...
# @cat Component art (web catalog)
# @icon art-angled
#
# Close-up insets for the assembly manual: a few named parts per picture,
# context ghosted or hidden, optional explode, optional section cut, a camera
# per shot, on a WIDE canvas, in the same style and lighting as the Iso30
# sprites. Exports transparent PNGs named <shot-id>_<variant>.png, plus
# _diagnostics.txt (human) and _closeups.json (machine), into
# Z:\Sketchup\BoothBuilderViews\AssemblyCloseups\ by default.
#
# NO TEXT IS BAKED INTO THE IMAGES. Callout labels are drawn by the app, so the
# rig exports the PIXEL POSITION of each named 3D point ("anchor") per image,
# and the app draws the leader lines in its own type. Rewording a callout never
# needs a re-export.
#
# ===========================================================================
# THE CONTRACT
#
#   * The model is RESTORED EXACTLY. Each shot runs inside its own
#     start_operation / abort_operation, so staging, explodes, ghosting, the
#     section plane and every hidden flag are undone. Camera, style, shading
#     and tag visibility are put back in an ensure. Definitions a shot loaded
#     from disk that survive the abort are removed again. A fingerprint of the
#     model is taken before and after the run and the diff is printed and
#     written — "restored" is a measured claim, not a hope.
#   * NOTHING IS SAVED. There is no save call in this file, and under the
#     bridge any save raises.
#   * A SHOT IS NEVER DRAWN HALF-EMPTY. A part that cannot be found is a MODEL
#     GAP: the shot is skipped and named, never rendered without it (the
#     save-scene-components.rb rule). Parts marked "optional" are the exception.
#
# WHERE THE SHOTS COME FROM
#
#   scripts/am-closeups.json, GENERATED by scripts/gen-am-closeups.py from the
#   scoper's shot-list.csv (titles, steps, priorities, prose) plus
#   scripts/am-closeups-poses.json (the machine pose for each shot that has
#   been posed). Edit the poses file and re-run the generator; never edit
#   am-closeups.json by hand.
#
# HOW A SHOT IS STAGED — stage, don't hunt
#
#   Every part named in the pose is placed as a FRESH instance inside one
#   staging group, and everything else at top level is hidden. A part comes
#   from, first that resolves:
#     def   a definition already in the open model, placed at its own origin
#     file  <component_root>\<file>.skp (NewMasterComponentList), loaded at its origin
#     find  an instance anywhere in the open model (nested too), copied at its
#           WORLD position — this is how Benton's posed models are reused
#   "split": n explodes the staged copy n levels so its children can be moved,
#   ghosted or hidden one by one. Exploding a STAGED copy never edits a shared
#   definition; that is the reason for staging at all.
#
# Order per shot: stage -> split -> moves -> section axis -> camera -> anchors
# -> hides -> ghosts -> section plane -> render -> anchor-check render -> abort.
# Anchors are resolved BEFORE ghosting, because ghosting flattens a part to raw
# faces and its named children stop existing.
#
# STYLE AND LIGHTING = the Iso30 contract (wr-shading.rb): "Style: Interior",
# Dark 45, Light 80, sun-for-shading off, shadows off, ground/sky/fog/
# watermark/AO off, transparent background, then fix-angled-alpha.py over the
# folder (the new graphics engine's 75% dark composite). There is NO ambient-
# occlusion pass: the last Iso30 run (DoorCombos/extra) saved ao="" in
# SketchUp's prefs, which that rig reads as off, so the sprites these sit
# beside were shot without it. All of it is set inside each shot's operation.
#
# ANCHORS are projected ANALYTICALLY from the camera (parallel: scale =
# image height / view height), not read off view.screen_coords, because the
# viewport's aspect is not the export's. The anchor-check pass renders a red
# dot at every anchor into _anchorcheck\<stem>.png with everything else hidden;
# scripts/am-closeup-check.py measures each dot against the JSON and fails any
# anchor more than 6 px out. That is the evidence the projection is right.
#
# RUN IT
#   Panel: WhisperRoom > Component art > Assembly close-ups.
#   Bridge (no dialogs):
#     python scripts/sketchup-bridge.py eval "load File.join(WhisperRoom::Tools::SCRIPTS_DIR, 'am-closeup-export.rb'); WR_AmCloseups.run('shots' => 'pilot', 'dry' => true)" --timeout 600 --write-root "Z:/Sketchup/BoothBuilderViews/AssemblyCloseups"
#   then the same with 'dry' => false. WR_AmCloseups.survey('duct box') lists
#   every definition matching a pattern, with sizes and where its instances sit,
#   for fixing a MODEL GAP.
#
#   load "C:/Users/bento/Documents/Claude/Sketchup/scripts/am-closeup-export.rb"

require 'sketchup.rb'
require 'json'
require 'fileutils'

module WR_AmCloseups
  RIG_VERSION = '1.1.0'.freeze
  PREF = 'WR_AmCloseups'.freeze
  DEF_OUT = 'Z:/Sketchup/BoothBuilderViews/AssemblyCloseups'.freeze

  WALK_MAX_DEPTH = 12
  WALK_MAX_NODES = 400_000
  FLATTEN_ROUNDS = 16

  # Rendering-option keys this rig sets on top of wr-shading.rb's contract.
  # Saved, read back and restored like the rest.
  SECTION_RO = { 'DisplaySectionPlanes' => false,
                 'DisplaySectionCuts'   => true,
                 'SectionCutFilled'     => true,
                 'SectionDefaultFillColor' => Sketchup::Color.new(150, 152, 156),
                 'Texture'              => true,
                 'DrawSilhouettes'      => true,
                 'SilhouetteWidth'      => 2,
                 'RenderMode'           => 2,
                 'SectionCutDrawEdges'  => true }.freeze

  # ------------------------------------------------------------- locations --

  # The folder this file and its JSON live in. Under the bridge a job's
  # __FILE__ is the bridge's run/ copy, so the plugin's SCRIPTS_DIR is tried
  # too; the first one holding the spec wins.
  def self.scripts_dir
    cands = [File.dirname(File.expand_path(__FILE__))]
    cands << WhisperRoom::Tools::SCRIPTS_DIR if defined?(WhisperRoom::Tools::SCRIPTS_DIR)
    cands.find { |d| File.exist?(File.join(d, 'am-closeups.json')) } || cands.last
  end

  def self.load_shading
    load File.join(scripts_dir, 'wr-shading.rb')
  end

  # =================================================== PURE (rbtest-lifted) ==
  #
  # Everything from here to the next banner is plain Ruby on arrays and hashes
  # — no Sketchup or Geom class — so scripts/rbtest-closeups.py can lift each
  # method verbatim and run it outside SketchUp. Keep it that way: a method
  # here that touches the API makes the offline test lie.

  def self.vsub(a, b)
    [a[0] - b[0], a[1] - b[1], a[2] - b[2]]
  end

  def self.vadd(a, b)
    [a[0] + b[0], a[1] + b[1], a[2] + b[2]]
  end

  def self.vscale(a, s)
    [a[0] * s, a[1] * s, a[2] * s]
  end

  def self.vdot(a, b)
    a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
  end

  def self.vcross(a, b)
    [a[1] * b[2] - a[2] * b[1],
     a[2] * b[0] - a[0] * b[2],
     a[0] * b[1] - a[1] * b[0]]
  end

  def self.vlen(a)
    Math.sqrt(a[0] * a[0] + a[1] * a[1] + a[2] * a[2])
  end

  def self.vnorm(a)
    l = vlen(a)
    return [0.0, 0.0, 0.0] if l < 1e-12
    [a[0] / l, a[1] / l, a[2] / l]
  end

  # Eye direction FROM the target — the Iso30 formula, unrounded.
  #   x = cos(elev) cos(azim)   y = cos(elev) sin(azim)   z = sin(elev)
  def self.cam_dir(azim, elev)
    e = elev.to_f * Math::PI / 180.0
    a = azim.to_f * Math::PI / 180.0
    [Math.cos(e) * Math.cos(a), Math.cos(e) * Math.sin(a), Math.sin(e)]
  end

  # Horizontal azimuth of a vector, degrees, or nil when it is vertical.
  def self.azim_of(v)
    return nil if Math.sqrt(v[0] * v[0] + v[1] * v[1]) < 1e-9
    Math.atan2(v[1], v[0]) * 180.0 / Math::PI
  end

  # [fwd, right, up] for an eye direction. fwd points from the eye to the
  # target. right = fwd x Z and up = right x fwd, exactly as the Iso30 rig's
  # basis; straight up or down falls back to +Y so the cross never collapses.
  def self.basis(dir)
    fwd = vnorm([-dir[0], -dir[1], -dir[2]])
    ref = fwd[2].abs > 0.999 ? [0.0, 1.0, 0.0] : [0.0, 0.0, 1.0]
    right = vnorm(vcross(fwd, ref))
    up = vcross(right, fwd)
    [fwd, right, up]
  end

  # Pixel position of a model point in the exported image: origin top-left,
  # x right, y DOWN. cam carries :w :h :target :right :up and, for parallel,
  # :height (the view height in inches = the image height); for perspective
  # :eye :fwd :fov (vertical, degrees). nil when the point is behind the eye.
  def self.project(p, cam)
    w = cam[:w].to_f
    h = cam[:h].to_f
    if cam[:persp]
      v = vsub(p, cam[:eye])
      z = vdot(v, cam[:fwd])
      return nil if z <= 1e-9
      f = (h / 2.0) / Math.tan(cam[:fov].to_f * Math::PI / 360.0)
      [w / 2.0 + vdot(v, cam[:right]) / z * f, h / 2.0 - vdot(v, cam[:up]) / z * f]
    else
      v = vsub(p, cam[:target])
      s = h / cam[:height].to_f
      [w / 2.0 + vdot(v, cam[:right]) * s, h / 2.0 - vdot(v, cam[:up]) * s]
    end
  end

  def self.in_frame?(xy, w, h)
    !xy.nil? && xy[0] >= 0.0 && xy[0] <= w.to_f && xy[1] >= 0.0 && xy[1] <= h.to_f
  end

  # The view height a set of points needs under this basis, so that every
  # point lands inside a w x h frame centred on the target, plus a margin.
  def self.fit_height(points, target, right, up, w, h, margin)
    aspect = w.to_f / h.to_f
    half = 0.0
    points.each do |p|
      v = vsub(p, target)
      half = [half, vdot(v, up).abs, vdot(v, right).abs / aspect].max
    end
    [half * 2.0 * (1.0 + margin.to_f), 1.0].max
  end

  # A point inside an axis-aligned box: at = [u, v, w] fractions per axis.
  def self.bbox_at(mn, mx, at)
    a = at || [0.5, 0.5, 0.5]
    [mn[0] + (mx[0] - mn[0]) * a[0].to_f,
     mn[1] + (mx[1] - mn[1]) * a[1].to_f,
     mn[2] + (mx[2] - mn[2]) * a[2].to_f]
  end

  def self.box_union(boxes)
    mn = [Float::INFINITY, Float::INFINITY, Float::INFINITY]
    mx = [-Float::INFINITY, -Float::INFINITY, -Float::INFINITY]
    boxes.each do |b|
      3.times do |i|
        mn[i] = b[0][i] if b[0][i] < mn[i]
        mx[i] = b[1][i] if b[1][i] > mx[i]
      end
    end
    [mn, mx]
  end

  def self.box_centre(b)
    [(b[0][0] + b[1][0]) / 2.0, (b[0][1] + b[1][1]) / 2.0, (b[0][2] + b[1][2]) / 2.0]
  end

  # Gap between two boxes (0 when they touch or overlap), inches.
  def self.box_gap(a, b)
    d = 0.0
    3.times do |i|
      g = [b[0][i] - a[1][i], a[0][i] - b[1][i], 0.0].max
      d += g * g
    end
    Math.sqrt(d)
  end

  # A definition name as it is compared: SketchUp's "#1" instance-of-a-copy
  # suffix dropped, whitespace trimmed. Component FILE names carry "_" where
  # the definition has an inch mark, so name_hit? tries both spellings.
  def self.base_name(n)
    n.to_s.strip.sub(/#\d+\z/, '')
  end

  def self.name_hit?(re, n)
    b = base_name(n)
    !(b =~ re).nil? || !(b.tr('"', '_') =~ re).nil?
  end

  def self.same_name?(a, b)
    x = base_name(a).downcase
    y = base_name(b).downcase
    x == y || x.tr('"', '_') == y.tr('"', '_')
  end

  # Order a selection, then take one, several or all. items are hashes with
  # :box => [min, max]. rank: x_asc x_desc y_asc y_desc z_asc z_desc xyz
  # (default, position order), view_near / view_far (needs the camera's fwd
  # and eye). index: an integer (negative counts from the end), 'first',
  # 'last', 'mid', 'all', or an array of integers.
  def self.rank_pick(items, rank, index, fwd = nil, eye = nil)
    return [] if items.empty?
    key = lambda do |it|
      c = box_centre(it[:box])
      case rank.to_s
      when 'x_asc'  then [c[0]]
      when 'x_desc' then [-c[0]]
      when 'y_asc'  then [c[1]]
      when 'y_desc' then [-c[1]]
      when 'z_asc'  then [c[2]]
      when 'z_desc' then [-c[2]]
      when 'view_near', 'view_far'
        d = fwd && eye ? vdot(vsub(c, eye), fwd) : 0.0
        [rank.to_s == 'view_near' ? d : -d]
      else [c[0].round(3), c[1].round(3), c[2].round(3)]
      end
    end
    sorted = items.sort_by { |it| key.call(it) }
    n = sorted.length
    case index
    when nil, 'all' then sorted
    when 'first' then [sorted[0]]
    when 'last'  then [sorted[n - 1]]
    when 'mid'   then [sorted[n / 2]]
    when Array   then index.map { |i| sorted[i.to_i] }.compact
    else
      i = index.to_i
      i += n if i < 0
      i >= 0 && i < n ? [sorted[i]] : []
    end
  end

  # A variant's pose is the shot's base pose with the variant's keys laid over
  # it, one level deep: a variant that names "parts" replaces the base's parts
  # wholesale. Keys starting with "_" are comments and are dropped.
  def self.merge_pose(base, var)
    out = {}
    (base || {}).each { |k, v| out[k] = v unless k.to_s.start_with?('_') }
    (var || {}).each { |k, v| out[k] = v unless k.to_s.start_with?('_') }
    out
  end

  # Which shot/variant pairs a "Shots" field asks for.
  #   pilot        every posed shot's pilot_variants
  #   all          every variant of every posed shot
  #   CU-03,CU-06  every variant of those shots
  #   CU-06:seated one variant
  # poses is {id => {'variants' => {name => {...}}, 'pilot_variants' => [...]}}.
  # Returns [[id, variant], ...] and a list of tokens that matched nothing.
  def self.pick_shots(poses, spec)
    s = spec.to_s.strip
    s = 'pilot' if s.empty?
    out = []
    miss = []
    ids = poses.keys.sort
    if s.downcase == 'pilot' || s.downcase == 'all'
      ids.each do |id|
        vs = (poses[id]['variants'] || {}).keys
        vs = Array(poses[id]['pilot_variants']) & vs if s.downcase == 'pilot'
        vs.each { |v| out << [id, v] }
      end
      return [out, miss]
    end
    s.split(',').map(&:strip).reject(&:empty?).each do |tok|
      id, var = tok.split(':', 2).map(&:strip)
      key = ids.find { |k| k.downcase == id.to_s.downcase }
      if key.nil?
        miss << tok
        next
      end
      vs = (poses[key]['variants'] || {}).keys
      if var && !var.empty?
        if vs.include?(var)
          out << [key, var]
        else
          miss << tok
        end
      else
        vs.each { |v| out << [key, v] }
      end
    end
    [out.uniq, miss]
  end

  # Filenames: <shot-id>_<variant>.png, with only what Windows refuses
  # replaced (the angled rig's rule — never slugify).
  def self.safe_name(name)
    out = name.to_s.strip.gsub(/[<>:"\/\\|?*\x00-\x1f]/, '-')
    out = out.sub(/[. ]+\z/, '')
    out.empty? ? 'unnamed' : out
  end

  def self.r3(v)
    (v.to_f * 1000.0).round / 1000.0
  end

  # ================================================= END OF THE PURE BLOCK ==

  # ------------------------------------------------------------ geometry IO --

  def self.arr(p)
    [p.x.to_f, p.y.to_f, p.z.to_f]
  end

  def self.p3(a)
    Geom::Point3d.new(a[0].to_f, a[1].to_f, a[2].to_f)
  end

  def self.v3(a)
    Geom::Vector3d.new(a[0].to_f, a[1].to_f, a[2].to_f)
  end

  def self.ident
    Geom::Transformation.new
  end

  def self.axis_vec(ax)
    return v3(ax) if ax.is_a?(Array)
    { 'x' => X_AXIS, 'y' => Y_AXIS, 'z' => Z_AXIS }[ax.to_s.downcase] || Z_AXIS
  end

  def self.ent_name(e)
    if e.is_a?(Sketchup::ComponentInstance)
      (e.definition.name.to_s rescue '')
    elsif e.is_a?(Sketchup::Group)
      n = (e.name.to_s rescue '')
      n.empty? ? ((e.definition.name.to_s rescue '')) : n
    else
      e.class.name.split('::').last
    end
  end

  def self.inst?(e)
    e.is_a?(Sketchup::ComponentInstance) || e.is_a?(Sketchup::Group)
  end

  def self.sub_ents(e)
    return e.entities if e.is_a?(Sketchup::Group)
    return e.definition.entities if e.is_a?(Sketchup::ComponentInstance)
    nil
  end

  def self.defn_of(e)
    return e.definition if e.is_a?(Sketchup::ComponentInstance)
    return (e.definition rescue e.entities.parent) if e.is_a?(Sketchup::Group)
    nil
  end

  # Box of a definition's raw bounds carried through a transformation.
  def self.raw_box(e, tr)
    d = defn_of(e)
    b = d ? d.bounds : (e.bounds rescue nil)
    return nil if b.nil? || !b.valid?
    pts = (0..7).map { |i| arr(b.corner(i).transform(d ? tr * e.transformation : tr)) }
    box_union(pts.map { |p| [p, p] })
  end

  # Visible-geometry box: faces only, hidden entities and off tags skipped —
  # the angled rig's rule, because a swing arc or a hidden helper inside a
  # part would otherwise move an anchor by inches. Falls back to raw bounds.
  def self.vis_walk(ents, tr, acc, st, depth)
    ents.each do |e|
      break if st[:n] >= WALK_MAX_NODES
      st[:n] += 1
      next if (e.hidden? rescue false)
      l = (e.layer rescue nil)
      next if l && !(l.visible? rescue true)
      if e.is_a?(Sketchup::Face)
        e.vertices.each { |v| acc << arr(v.position.transform(tr)) }
        st[:faces] += 1
      elsif inst?(e) && depth < WALK_MAX_DEPTH
        sub = sub_ents(e)
        vis_walk(sub, tr * e.transformation, acc, st, depth + 1) if sub
      end
    end
  end

  def self.vis_box(e, ptr)
    if inst?(e)
      acc = []
      st = { :n => 0, :faces => 0 }
      vis_walk(sub_ents(e), ptr * e.transformation, acc, st, 0)
      return box_union(acc.map { |p| [p, p] }) unless acc.empty?
      return raw_box(e, ptr)
    end
    b = (e.bounds rescue nil)
    return nil if b.nil? || !b.valid?
    box_union([[arr(b.min.transform(ptr)), arr(b.min.transform(ptr))],
               [arr(b.max.transform(ptr)), arr(b.max.transform(ptr))]])
  end

  # Every component instance and group in the model, nested ones included,
  # with its WORLD transformation and the names of its ancestors. The staging
  # group is skipped. Built once per run: shots are aborted, so the model the
  # index describes does not change between them.
  def self.instance_index(model, skip, ents = nil)
    out = []
    st = { :n => 0 }
    # :mat is the material the instance RENDERS with: its own, else the
    # nearest painted ancestor's (SketchUp paints default faces that way).
    # A re-instanced copy has to carry it, or a painted wall comes out white.
    walk = lambda do |ents, tr, path, depth, pmat|
      ents.each do |e|
        break if st[:n] >= WALK_MAX_NODES
        next unless inst?(e)
        next if skip && e == skip
        st[:n] += 1
        wtr = tr * e.transformation
        nm = ent_name(e)
        mat = (e.material rescue nil) || pmat
        out << { :ent => e, :tr => wtr, :ptr => tr, :name => nm, :path => path, :mat => mat }
        walk.call(sub_ents(e), wtr, path + [nm], depth + 1, mat) if depth < WALK_MAX_DEPTH
      end
    end
    walk.call(ents || model.entities, ident, [], 0, nil)
    [out, st[:n] >= WALK_MAX_NODES]
  end

  # --------------------------------------------------------- the fingerprint --

  def self.cam_sig(c)
    s = [arr(c.eye).map { |v| r3(v) }, arr(c.target).map { |v| r3(v) },
         arr(c.up).map { |v| r3(v) }, c.perspective?]
    s << (c.perspective? ? r3(c.fov) : r3((c.height rescue 0)))
    s << r3((c.aspect_ratio rescue 0))
    s
  end

  def self.fingerprint(model)
    ents = model.entities
    ro = model.rendering_options
    si = model.shadow_info
    keys = WR_Shading::TRANSPARENCY.keys + SECTION_RO.keys
    {
      'title'          => model.title.to_s,
      'path'           => model.path.to_s,
      'entities'       => ents.length,
      'hidden_top'     => ents.count { |e| (e.hidden? rescue false) },
      'definitions'    => model.definitions.length,
      'materials'      => model.materials.length,
      'layers_visible' => model.layers.map { |l| "#{l.name}=#{(l.visible? rescue '?')}" }.join('|'),
      'pages'          => model.pages.count,
      'selected_page'  => (model.pages.selected_page ? model.pages.selected_page.name : ''),
      'style'          => (model.styles.selected_style.name rescue ''),
      'active_section' => ((ents.active_section_plane ? 'set' : 'none') rescue 'n/a'),
      'active_path'    => (model.active_path ? model.active_path.length : 0),
      'rendering'      => keys.map { |k| "#{k}=#{(ro[k] rescue 'n/a')}" }.join('|'),
      'shadow'         => WR_Shading::SHADOW_KEYS.map { |k| "#{k}=#{(si[k] rescue 'n/a')}" }.join('|'),
      'camera'         => cam_sig(model.active_view.camera).inspect,
      'modified'       => (model.modified? rescue 'n/a')
    }
  end

  def self.fp_diff(a, b)
    a.keys.reject { |k| a[k] == b[k] }.map { |k| "#{k}: #{a[k]} -> #{b[k]}" }
  end

  # -------------------------------------------------------- style + camera --

  def self.push_section_ro(model)
    ro = model.rendering_options
    saved = {}
    stuck = []
    SECTION_RO.each do |k, v|
      saved[k] = (ro[k] rescue nil)
      next if saved[k].nil?   # key not in this SketchUp: nothing to set or restore
      begin
        ro[k] = v
      rescue StandardError => e
        stuck << "#{k}: write raised #{e.class}"
        next
      end
      got = (ro[k] rescue :unreadable)
      stuck << "#{k}: wanted #{v.inspect}, still #{got.inspect}" unless got == v
    end
    [saved, stuck]
  end

  def self.pop_section_ro(model, saved)
    ro = model.rendering_options
    (saved || {}).each { |k, v| (ro[k] = v) rescue nil unless v.nil? }
  end

  def self.save_camera(view)
    c = view.camera
    { :eye => c.eye, :target => c.target, :up => c.up, :persp => c.perspective?,
      :fov => (c.fov rescue nil), :height => (c.height rescue nil),
      :aspect => (c.aspect_ratio rescue 0.0) }
  end

  def self.restore_camera(view, s)
    return if s.nil?
    c = view.camera
    # Projection FIRST: switching parallel -> perspective after set() lets
    # SketchUp re-derive the eye distance, and the restored camera drifted.
    c.perspective = s[:persp]
    c.set(s[:eye], s[:target], s[:up])
    (c.aspect_ratio = s[:aspect].to_f) rescue nil
    if s[:persp]
      (c.fov = s[:fov]) rescue nil if s[:fov]
    else
      (c.height = s[:height]) rescue nil if s[:height]
    end
    view.refresh rescue nil
  end

  def self.close_contexts(model)
    n = 0
    while model.active_path && n < 20
      break unless model.close_active
      n += 1
    end
    n
  rescue StandardError
    n
  end

  # ------------------------------------------------------------------ spec --

  def self.load_spec(path = nil)
    path ||= File.join(scripts_dir, 'am-closeups.json')
    raise "close-up spec not found: #{path}" unless File.exist?(path)
    spec = JSON.parse(File.read(path, :encoding => 'UTF-8'))
    spec['_path'] = path
    spec
  end

  def self.rig_value(rig, key, default)
    rig.key?(key) ? rig[key] : default
  end

  def self.rx(s)
    Regexp.new(s.to_s, Regexp::IGNORECASE)
  end

  # ================================================================ STAGING ==

  # One source descriptor -> [definition, transformation, how] or nil.
  def self.resolve_source(ctx, src, part)
    model = ctx[:model]
    if src['def']
      d = model.definitions.find { |x| !x.image? && same_name?(x.name, src['def']) }
      return [d, ident, "definition in this model: #{d.name}"] if d
    end
    if src['file']
      path = src['file'].to_s
      unless path =~ /\A[A-Za-z]:[\\\/]/ || path.start_with?('/')
        # component_root first, then any component_fallback_roots (the
        # shipped poses use none: NewMasterComponentList only, per Benton).
        cands = Array(ctx[:roots] || [ctx[:root]]).map { |r| File.join(r, path) }
        path = cands.find { |c| File.exist?(c) } || cands.first || path
      end
      if File.exist?(path)
        d = (model.definitions.load(path) rescue nil)
        if d
          ctx[:loaded] << d.name
          return [d, ident, "loaded from #{path} -> #{d.name}"]
        end
        ctx[:warnings] << "#{part['role']}: #{path} exists but SketchUp would not load it"
      else
        ctx[:warnings] << "#{part['role']}: file not found: #{path}" unless src['def']
      end
    end
    nil
  end

  # A "find" source: every instance in the model whose definition name
  # matches, filtered by ancestor ("within") and distance ("near"), then
  # picked. Returns [[definition, world transformation, how], ...].
  def self.resolve_find(ctx, src, part)
    index = if src['in_file']
              # A find inside a FILE (an assembled booth on disk) rather than the
              # open model. run() loaded it once, outside every operation; its
              # instances are walked from the definition at the identity.
              key = src['in_file'].to_s
              d = (ctx[:infile] || {})[key]
              if d.nil? || !d.valid?
                ctx[:warnings] << "#{part['role']}: in_file #{key} was not preloaded"
                return []
              end
              (ctx[:infile_index] ||= {})[key] ||= instance_index(ctx[:model], nil, d.entities)[0]
            else
              ctx[:index] ||= begin
                idx, capped = instance_index(ctx[:model], ctx[:s])
                ctx[:warnings] << "the model walk stopped at #{WALK_MAX_NODES} nodes; a find may miss parts" if capped
                idx
              end
            end
    re = rx(src['find'])
    hits = index.select { |it| name_hit?(re, it[:name]) }
    hits = hits.select { |it| it[:ent].valid? }
    if src['within']
      wre = rx(src['within'])
      hits = hits.select { |it| it[:path].any? { |n| name_hit?(wre, n) } }
    end
    groups = hits.select { |it| it[:ent].is_a?(Sketchup::Group) }
    unless groups.empty?
      ctx[:warnings] << "#{part['role']}: #{groups.length} match(es) are Groups, which cannot be " \
                        're-instanced; only component instances are used'
    end
    hits = hits.reject { |it| it[:ent].is_a?(Sketchup::Group) }
    hits.each { |it| it[:box] ||= raw_box(it[:ent], it[:ptr]) }
    hits = hits.select { |it| it[:box] }
    # "region": [[x0, y0, z0], [x1, y1, z1]] keeps the hits whose box centre
    # lies inside — for picking one copy out of an assembled booth by place.
    if src['region'].is_a?(Array) && src['region'].length == 2
      lo, hi = src['region']
      hits = hits.select do |it|
        c = box_centre(it[:box])
        (0..2).all? { |i| c[i] >= lo[i].to_f && c[i] <= hi[i].to_f }
      end
    end
    # Coincident copies (a posed model can hold the same booth several times
    # over, one per scene) would stage twice on the same spot and z-fight.
    seen = {}
    hits = hits.select do |it|
      k = [base_name(it[:name])] + it[:box].flatten.map { |v| (v * 100).round }
      seen[k] ? false : (seen[k] = true)
    end
    fwd = eye = nil
    if src['near']
      ref = ctx[:roles][src['near']['role']]
      if ref.nil? || ref.empty?
        ctx[:warnings] << "#{part['role']}: near-role #{src['near']['role']} is not staged (list it first)"
        return []
      end
      rb = box_union(ref.map { |pc| pc[:box] || vis_box(pc[:ent], ident) }.compact)
      gap = (src['near']['gap'] || 2.0).to_f
      hits = hits.select { |it| box_gap(it[:box], rb) <= gap }
      rc = box_centre(rb)
      hits = hits.sort_by { |it| vlen(vsub(box_centre(it[:box]), rc)) }
      picked = case src['pick']
               when nil then hits.first(1)
               when 'all' then hits
               when Array then src['pick'].map { |i| hits[i.to_i] }.compact
               else [hits[src['pick'].to_i]].compact
               end
    else
      picked = rank_pick(hits, src['rank'] || 'xyz', src.key?('pick') ? src['pick'] : 0, fwd, eye)
    end
    picked.map do |it|
      [it[:ent].definition, it[:tr],
       "found #{it[:name]} at #{arr(it[:tr].origin).map { |v| v.round(2) }.inspect} " \
       "in #{it[:path].empty? ? 'top level' : it[:path].join(' > ')} (#{hits.length} candidate(s))" \
       "#{it[:mat] ? ", material #{it[:mat].name}" : ''}", it[:mat]]
    end
  end

  def self.stage_part(ctx, part)
    srcs = part['sources'] || [part['source']].compact
    placed = []
    how = nil
    srcs.each do |src|
      got = if src['find']
              resolve_find(ctx, src, part)
            else
              r = resolve_source(ctx, src, part)
              r ? [r] : []
            end
      next if got.empty?
      # "at" is one offset [x, y, z] or a list of them (one copy per offset);
      # "rot" is a list of [axis, degrees] turns about the part's own origin,
      # applied before the offset; "mirror" is an axis to reflect across.
      ats = src['at'] || part['at']
      ats = [ats] if ats.is_a?(Array) && ats.first.is_a?(Numeric)
      ats = [nil] if ats.nil? || ats.empty?
      rots = src['rot'] || part['rot'] || []
      mir = src['mirror'] || part['mirror']
      got.each do |defn, tr, h, fmat|
        ats.each do |at|
          host = part['level'] ? (ctx[:levels][part['level'].to_i] || ctx[:s]) : ctx[:s]
          inst = host.entities.add_instance(defn, tr)
          inst.material = fmat if fmat && fmat.valid?
          if mir
            sv = [1.0, 1.0, 1.0]
            sv[%w[x y z].index(mir.to_s)] = -1.0
            inst.transform!(Geom::Transformation.scaling(ORIGIN, sv[0], sv[1], sv[2]))
          end
          rots.each do |ax, deg|
            inst.transform!(Geom::Transformation.rotation(ORIGIN, axis_vec(ax), deg.to_f * Math::PI / 180.0))
          end
          inst.transform!(Geom::Transformation.translation(v3(at))) if at
          inst.material = paint_material(ctx[:model], part['paint']) if part['paint']
          placed << { :ent => inst, :name => defn.name, :role => part['role'] }
        end
        how = h
      end
      if part['generated'] && !got.empty?
        ctx[:generated] << (part['generated'].is_a?(String) ? part['generated'] : got.first[0].name)
      end
      break
    end
    [placed, how]
  end

  # Explode staged copies n levels so their children become separate pieces.
  # The set difference of the staging group's entities before and after is
  # the truth about what appeared — not explode's return value.
  def self.split!(ctx, pieces, levels, keep)
    keep_re = keep ? rx(keep) : nil
    levels.to_i.times do
      nxt = []
      pieces.each do |pc|
        e = pc[:ent]
        if e.valid? && inst?(e) && !(keep_re && name_hit?(keep_re, pc[:name]))
          s = e.parent
          before = s.entities.to_a
          e.explode
          fresh = s.entities.to_a - before
          fresh.each { |x| nxt << { :ent => x, :name => ent_name(x), :role => pc[:role] } }
        else
          nxt << pc
        end
      end
      pieces = nxt
    end
    # Loose edges and faces stay pieces (they render), but only instances and
    # groups have names worth selecting by.
    pieces
  end

  # Every nested instance under a role's pieces, with its parent's world
  # transformation, the piece itself first. For anchors on parts that were
  # not split out (hinges inside a door assembly).
  def self.deep_items(pieces)
    out = []
    st = { :n => 0 }
    walk = lambda do |e, ptr, depth|
      return if st[:n] >= WALK_MAX_NODES
      st[:n] += 1
      out << { :ent => e, :ptr => ptr, :name => ent_name(e) }
      return unless inst?(e) && depth < WALK_MAX_DEPTH
      sub_ents(e).each { |c| walk.call(c, ptr * e.transformation, depth + 1) if inst?(c) }
    end
    pieces.each { |pc| walk.call(pc[:ent], ident, 0) if pc[:ent].valid? }
    out
  end

  # A selector -> the pieces it names, each with :box. spec: part, match,
  # deep, rank, index.
  def self.select(ctx, spec, default_index = 'all')
    return [] unless spec.is_a?(Hash)
    pcs = ctx[:roles][spec['part']]
    return [] if pcs.nil? || pcs.empty?
    items = if spec['deep']
              deep_items(pcs)
            else
              pcs.select { |pc| pc[:ent].valid? }.map { |pc| { :ent => pc[:ent], :ptr => ident, :name => pc[:name], :pc => pc } }
            end
    if spec['loose']
      # The faces and edges a split left behind (the parent's own geometry,
      # e.g. a door frame once its nested hinges and adaptors are split out).
      items = items.reject { |it| inst?(it[:ent]) }
    elsif spec['name']
      # Exact definition name, "#n" kept: the only handle on Benton's unnamed
      # "Component#223"-style children, which base_name would collapse.
      want = Array(spec['name']).map(&:to_s)
      items = items.select { |it| inst?(it[:ent]) && want.include?(it[:name].to_s) }
    elsif spec['match']
      re = rx(spec['match'])
      items = items.select { |it| inst?(it[:ent]) && name_hit?(re, it[:name]) }
    end
    if spec['not']
      nre = rx(spec['not'])
      items = items.reject { |it| inst?(it[:ent]) && name_hit?(nre, it[:name]) }
    end
    items.each { |it| it[:box] ||= vis_box(it[:ent], it[:ptr]) }
    items = items.select { |it| it[:box] }
    cam = ctx[:cam]
    idx = spec.key?('index') ? spec['index'] : default_index
    rank_pick(items, spec['rank'] || 'xyz', idx, cam && cam[:fwd], cam && cam[:eye])
  end

  # ------------------------------------------------------------- holes --
  #
  # Bolt holes are modelled in the library as full circles (ArcCurves) of
  # radius ~0.25 in, one at each face a hole passes through. holes_in returns
  # them in world space: [centre, unit normal, radius].
  def self.holes_in(pieces, rmin, rmax)
    out = []
    st = { :n => 0 }
    walk = lambda do |ents, tr, depth|
      seen = {}
      ents.grep(Sketchup::Edge).each do |e|
        c = e.curve
        next unless c.is_a?(Sketchup::ArcCurve) && !seen[c]
        seen[c] = true
        next unless (c.end_angle - c.start_angle).abs > 6.0
        r = c.radius.to_f * (c.xaxis.transform(tr).length.to_f / [c.xaxis.length.to_f, 1e-9].max)
        next if r < rmin || r > rmax
        out << [arr(c.center.transform(tr)), vnorm(arr(c.normal.transform(tr))), r]
      end
      return if depth > WALK_MAX_DEPTH
      ents.each do |e|
        next unless inst?(e)
        st[:n] += 1
        break if st[:n] > WALK_MAX_NODES
        walk.call(sub_ents(e), tr * e.transformation, depth + 1)
      end
    end
    pieces.each do |it|
      e = it[:ent]
      next unless e.valid?
      if inst?(e)
        walk.call(sub_ents(e), it[:ptr] * e.transformation, 0)
      elsif e.is_a?(Sketchup::Edge)
        walk.call([e], it[:ptr], 0)
      end
    end
    out
  end

  # One hole per bolt line: circles whose centres lie on one line along
  # `into` are the same hole seen at each face it passes through; the ENTRY
  # circle is the one furthest back against `into` (where the head bears).
  def self.hole_lines(holes, into)
    lines = []
    holes.each do |c, n, r|
      next if vdot(n, into).abs < 0.9
      off = vsub(c, vscale(into, vdot(c, into)))
      ln = lines.find { |l| vlen(vsub(l[:off], off)) < 0.08 }
      if ln
        ln[:pts] << c
      else
        lines << { :off => off, :pts => [c], :r => r }
      end
    end
    lines.map do |l|
      entry = l[:pts].min_by { |q| vdot(q, into) }
      exit_ = l[:pts].max_by { |q| vdot(q, into) }
      { :entry => entry, :exit => exit_, :r => l[:r], :depth => vdot(vsub(exit_, entry), into) }
    end
  end

  # A "bolts" entry: {role, of: selector, into: [x,y,z] (shank direction, world),
  #   r: [min, max], region: [[lo], [hi]], rank, pick, lift (in, back along -into),
  #   seat (in, head bearing face sits this far back from the entry circle),
  #   source: {file: ...}, generated: name}
  # Places one bolt per hole line found in the selected pieces.
  def self.place_bolts!(ctx, rec, bs)
    into = vnorm(bs['into'].map(&:to_f))
    sel = select(ctx, bs['of'] || {}, 'all')
    rr = bs['r'] || [0.15, 0.32]
    lines = hole_lines(holes_in(sel, rr[0].to_f, rr[1].to_f), into)
    if bs['region'].is_a?(Array)
      lo, hi = bs['region']
      lines = lines.select { |l| (0..2).all? { |i| l[:entry][i] >= lo[i].to_f && l[:entry][i] <= hi[i].to_f } }
    end
    items = lines.map { |l| { :box => [l[:entry], l[:entry]], :line => l } }
    picked = rank_pick(items, bs['rank'] || 'xyz', bs.key?('pick') ? bs['pick'] : 'all')
    role = (bs['role'] || 'bolts').to_s
    if picked.empty?
      msg = "#{role}: no bolt hole found in #{(bs['of'] || {}).to_json} along #{bs['into'].inspect}"
      return rec['warnings'] << "optional #{msg}" if bs['optional']
      rec['missing'] << msg
      return
    end
    src = bs['source'] || {}
    d, = resolve_source(ctx, src, { 'role' => role })
    if d.nil?
      rec['missing'] << "#{role}: bolt part did not load: #{src.to_json}"
      return
    end
    xa = v3(into)
    ya = (xa.parallel?(Z_AXIS) ? X_AXIS : Z_AXIS) * xa
    za = xa * ya
    placed = []
    picked.each do |it|
      l = it[:line]
      o = vsub(l[:entry], vscale(into, (bs['lift'] || 0).to_f + (bs['seat'] || 0).to_f))
      tr = Geom::Transformation.axes(p3(o), xa, ya.normalize, za.normalize)
      inst = ctx[:s].entities.add_instance(d, tr)
      pc = { :ent => inst, :name => d.name, :role => role }
      pc[:box] = vis_box(inst, ident)
      placed << pc
    end
    ctx[:roles][role] = (ctx[:roles][role] || []) + placed
    ctx[:generated] << (bs['generated'].is_a?(String) ? bs['generated'] : d.name) if bs['generated']
    rec['generated'] = ctx[:generated].uniq
    rec['bolts'] = (rec['bolts'] || []) << { 'role' => role, 'n' => placed.length,
                                             'holes_found' => lines.length, 'lift' => (bs['lift'] || 0) }
  end

  # A point spec -> [x, y, z] or nil. Forms:
  #   {"xyz": [x, y, z]}                       absolute, inches
  #   {"part": .., "match": .., "at": [u,v,w]} a point in the selection's box
  #   {"x": P, "y": P, "z": P}                 each coordinate from its own point
  # Any form may carry "fallback": another point spec.
  def self.point(ctx, spec, info = nil)
    return nil unless spec.is_a?(Hash)
    info ||= {}
    if spec['xyz']
      return spec['xyz'].map(&:to_f)
    end
    if spec['x'] || spec['y'] || spec['z']
      px = point(ctx, spec['x'], info)
      py = point(ctx, spec['y'], info)
      pz = point(ctx, spec['z'], info)
      return [px[0], py[1], pz[2]] if px && py && pz
    else
      items = select(ctx, spec, 'all')
      unless items.empty?
        info[:n] = (info[:n] || 0) + items.length
        b = box_union(items.map { |it| it[:box] })
        return bbox_at(b[0], b[1], spec['at'])
      end
    end
    if spec['fallback']
      info[:fallback] = true
      return point(ctx, spec['fallback'], info)
    end
    nil
  end

  # The local axes of a component instance mapped to world, with the part's
  # own extent along each — so "long" and "short" follow a rotated part.
  def self.part_axes(e, ptr)
    return nil unless e.is_a?(Sketchup::ComponentInstance)
    tr = ptr * e.transformation
    b = e.definition.bounds
    ext = [b.width.to_f, b.height.to_f, b.depth.to_f]
    axes = [tr.xaxis, tr.yaxis, tr.zaxis].map { |v| vnorm(arr(v)) }
    sc = [tr.xaxis.length.to_f, tr.yaxis.length.to_f, tr.zaxis.length.to_f]
    (0..2).map { |i| { :axis => axes[i], :extent => ext[i] * sc[i] } }
  end

  # Section geometry before the camera exists: a point and an UNORIENTED unit
  # axis. The camera may take its azimuth from the axis; the normal is then
  # turned to face the camera (the near side is what a section removes).
  def self.section_geom(ctx, sec)
    return nil unless sec.is_a?(Hash)
    items = select(ctx, sec, 'all')
    return nil if items.empty?
    b = box_union(items.map { |it| it[:box] })
    centre = box_centre(b)
    aitems = sec['axis_of'] ? select(ctx, sec['axis_of'], 0) : [items.first]
    ai = aitems.first || items.first
    ax = sec['axis'] || 'x'
    axis = nil
    extent = nil
    case ax
    when Array
      axis = vnorm(ax.map(&:to_f))
      extent = [b[1][0] - b[0][0], b[1][1] - b[0][1], b[1][2] - b[0][2]].max
    when 'x', 'y', 'z'
      i = %w[x y z].index(ax)
      axis = [0.0, 0.0, 0.0]
      axis[i] = 1.0
      extent = b[1][i] - b[0][i]
    when 'long', 'short'
      pa = part_axes(ai[:ent], ai[:ptr])
      if pa
        hz = pa.select { |a| a[:axis][2].abs < 0.5 }
        hz = hz.sort_by { |a| a[:extent] }
        pick = ax == 'long' ? hz.last : hz.first
        if pick
          axis = pick[:axis]
          extent = pick[:extent]
        end
      end
      if axis.nil?
        ab = ai[:box]
        dx = ab[1][0] - ab[0][0]
        dy = ab[1][1] - ab[0][1]
        longx = dx >= dy
        usex = ax == 'long' ? longx : !longx
        axis = usex ? [1.0, 0.0, 0.0] : [0.0, 1.0, 0.0]
        extent = usex ? (b[1][0] - b[0][0]) : (b[1][1] - b[0][1])
      end
    end
    return nil if axis.nil?
    at = (sec['at'] || 0.5).to_f
    pt = vadd(centre, vscale(axis, (at - 0.5) * extent.to_f))
    { :point => pt, :axis => axis, :n => items.length }
  end

  def self.view_height(pose, rig)
    cls = rig_value(rig, 'scale_classes', { 'S' => 24, 'M' => 48, 'L' => 96 })
    sc = pose['scale']
    return cls[sc].to_f if sc.is_a?(String) && cls[sc]
    return sc.to_f if sc.is_a?(Numeric)
    nil
  end

  def self.build_camera(ctx, pose, rig)
    c = pose['camera'] || {}
    w, h = ctx[:w], ctx[:h]
    all = box_union(ctx[:roles].values.flatten.select { |pc| pc[:ent].valid? }
                               .map { |pc| pc[:box] ||= vis_box(pc[:ent], ident) }.compact)
    all = [[-1.0, -1.0, -1.0], [1.0, 1.0, 1.0]] unless all[0][0].finite?
    target = c['target'] ? point(ctx, c['target']) : nil
    if target.nil?
      ctx[:warnings] << 'camera target did not resolve; aimed at the centre of everything staged' if c['target']
      target = box_centre(all)
    end
    azim = (c['azimuth'] || rig_value(rig, 'azimuth', 38)).to_f
    how = "azimuth #{azim}"
    if c['azimuth_toward'].is_a?(Array)
      pts = c['azimuth_toward'].map { |sp| point(ctx, sp) }
      if pts.all?
        sum = [0.0, 0.0, 0.0]
        pts.each do |p|
          v = vsub(p, target)
          sum = vadd(sum, vnorm([v[0], v[1], 0.0]))
        end
        a = azim_of(sum)
        if a
          azim = a
          how = "azimuth toward #{pts.length} point(s)"
        else
          ctx[:warnings] << 'azimuth_toward points cancel out; kept the numeric azimuth'
        end
      else
        ctx[:warnings] << 'azimuth_toward: a point did not resolve; kept the numeric azimuth'
      end
    elsif c['azimuth_along'] == 'section'
      a = ctx[:sec] ? azim_of(ctx[:sec][:axis]) : nil
      if a
        azim = a
        how = 'azimuth along the section normal'
      else
        ctx[:warnings] << 'azimuth_along section: no horizontal section axis; kept the numeric azimuth'
      end
    end
    azim += (c['azimuth_offset'] || 0).to_f
    elev = (c['elevation'] || rig_value(rig, 'elevation', 30)).to_f
    dir = cam_dir(azim, elev)
    fwd, right, up = basis(dir)
    persp = c['projection'] == 'perspective'
    height = c['height'].is_a?(Numeric) ? c['height'].to_f : view_height(pose, rig)
    if height.nil? || c['height'] == 'fit'
      corners = []
      [[0, 0, 0], [1, 0, 0], [0, 1, 0], [1, 1, 0], [0, 0, 1], [1, 0, 1], [0, 1, 1], [1, 1, 1]].each do |m|
        corners << [all[m[0]][0], all[m[1]][1], all[m[2]][2]]
      end
      height = fit_height(corners, target, right, up, w, h, (c['margin'] || 0.08))
    end
    radius = 0.0
    [all[0], all[1]].each { |p| radius = [radius, vlen(vsub(p, target))].max }
    dist = if persp
             (c['distance'] || 120.0).to_f
           else
             [height * 6.0, 1000.0, radius * 3.0].max
           end
    eye = vadd(target, vscale(dir, dist))
    { :eye => eye, :target => target, :dir => dir, :fwd => fwd, :right => right, :up => up,
      :persp => persp, :height => height, :fov => (c['fov'] || 35.0).to_f, :w => w, :h => h,
      :azim => azim, :elev => elev, :dist => dist, :how => how }
  end

  # "paint" on a part: the material its default-material faces take, as the
  # library does by painting the INSTANCE (a part loaded on its own arrives
  # unpainted and renders white). A name already in the model, or [r, g, b].
  def self.paint_material(model, spec)
    if spec.is_a?(String)
      m = model.materials[spec]
      return m if m
    end
    rgb = spec.is_a?(Array) ? spec.map(&:to_i) : [72, 72, 74]
    nm = format('WR_CU_paint_%02x%02x%02x', *rgb)
    m = model.materials[nm] || model.materials.add(nm)
    m.color = Sketchup::Color.new(*rgb)
    m
  end

  # THE FLAT STYLE (rig 1.1). Library parts carry a dark speckled felt
  # texture ("Booth Builder SRO") that swallows every edge at close-up
  # scale. Inside the shot's operation — so the abort takes it back — every
  # material the shot LOADED (never one the open model already had) loses
  # its texture and becomes a light panel grey, except the near-black ones
  # (black parts stay black) and the metals (a light silver).
  def self.flatten_materials!(model, before, rig)
    grey = Sketchup::Color.new(*(rig_value(rig, 'flat_grey', [214, 216, 219])))
    metal = Sketchup::Color.new(*(rig_value(rig, 'flat_metal', [188, 192, 198])))
    n = 0
    model.materials.each do |m|
      next if before.include?(m.name)
      next if m.name.start_with?('WR_CU_') || m.name.start_with?('WR GEN')
      c = m.color
      luma = (0.2126 * c.red + 0.7152 * c.green + 0.0722 * c.blue) / 255.0
      nm = m.name.downcase
      black = nm.include?('black') || (m.texture.nil? && luma < 0.18)
      next if black
      metallic = nm =~ /alumin|silver|chrome|metal|steel/
      m.texture = nil if m.texture
      m.color = metallic ? metal : grey
      n += 1
    end
    n
  rescue StandardError => e
    "flatten failed: #{e.class}: #{e.message}"
  end

  # The default from rig 1.1: every shot is FITTED (the subject fills
  # fit_fill of the frame, centred) unless the pose pins a numeric height.
  def self.fit_wanted?(p)
    c = p['camera'] || {}
    return false if c['height'].is_a?(Numeric) || c['fit'] == false
    return true if c['fit'] || c['height'] == 'fit'
    !p['scale'].is_a?(Numeric)
  end

  # Every visible leaf box of the shown pieces, as corner points. Hidden
  # pieces are skipped; a piece wholly on the removed side of an
  # axis-aligned section is skipped and a straddling one is clamped.
  def self.shown_points(ctx, sec_cut, only = nil)
    pts = []
    ctx[:roles].each do |role, pcs|
      next if only && !only.include?(role)
      pcs.each do |pc|
        e = pc[:ent]
        next unless e.valid?
        next if (e.hidden? rescue false)
        boxes = []
        if inst?(e)
          sub_ents(e).each do |c|
            next if (c.hidden? rescue false)
            b = inst?(c) ? vis_box(c, e.transformation) : nil
            boxes << b if b
          end
          fb = []
          sub_ents(e).grep(Sketchup::Face).each { |f| f.vertices.each { |v| q = arr(v.position.transform(e.transformation)); fb << [q, q] } }
          boxes << box_union(fb) unless fb.empty?
          boxes = [vis_box(e, ident)].compact if boxes.empty?
        else
          b = vis_box(e, ident)
          boxes << b if b
        end
        boxes.each do |b|
          b = [b[0].dup, b[1].dup]
          if sec_cut
            i, keep_hi, at = sec_cut
            if keep_hi
              next if b[1][i] < at
              b[0][i] = [b[0][i], at].max
            else
              next if b[0][i] > at
              b[1][i] = [b[1][i], at].min
            end
          end
          [[0, 0, 0], [1, 0, 0], [0, 1, 0], [1, 1, 0], [0, 0, 1], [1, 0, 1], [0, 1, 1], [1, 1, 1]].each do |m|
            pts << [b[m[0]][0], b[m[1]][1], b[m[2]][2]]
          end
        end
      end
    end
    pts
  end

  def self.fit_camera!(ctx, cam, p)
    c = p['camera'] || {}
    fill = (c['fill'] || 0.8).to_f
    sec_cut = nil
    if ctx[:sec]
      n = ctx[:sec][:axis]
      n = vscale(n, -1.0) if vdot(n, vsub(cam[:eye], ctx[:sec][:point])) < 0.0
      n = vscale(n, -1.0) if (p['section'] || {})['flip']
      i = (0..2).max_by { |k| n[k].abs }
      # The plane removes the side its normal points to (toward the camera);
      # what stays is the far side.
      sec_cut = [i, n[i] < 0, ctx[:sec][:point][i]] if n[i].abs > 0.99
    end
    pts = if c['fit_box'].is_a?(Array)
            # An explicit world box: the shot frames a REGION (the joint, the
            # hinge column), and parts may run out of frame beyond it.
            lo, hi = c['fit_box']
            [[0, 0, 0], [1, 0, 0], [0, 1, 0], [1, 1, 0], [0, 0, 1], [1, 0, 1], [0, 1, 1], [1, 1, 1]].map do |m|
              [(m[0] == 0 ? lo : hi)[0].to_f, (m[1] == 0 ? lo : hi)[1].to_f, (m[2] == 0 ? lo : hi)[2].to_f]
            end
          else
            shown_points(ctx, sec_cut, c['fit_roles'])
          end
    return cam if pts.empty?
    us = pts.map { |q| vdot(q, cam[:right]) }
    vs = pts.map { |q| vdot(q, cam[:up]) }
    w, h = cam[:w].to_f, cam[:h].to_f
    du = us.max - us.min
    dv = vs.max - vs.min
    height = [dv, du * h / w].max / fill
    height = [height, (c['min_height'] || 4.0).to_f].max
    mid_u = (us.max + us.min) / 2.0
    mid_v = (vs.max + vs.min) / 2.0
    t0 = cam[:target]
    shift = vadd(vscale(cam[:right], mid_u - vdot(t0, cam[:right])), vscale(cam[:up], mid_v - vdot(t0, cam[:up])))
    target = vadd(t0, shift)
    out = cam.dup
    out[:target] = target
    out[:eye] = vadd(target, vscale(cam[:dir], cam[:dist]))
    out[:height] = height unless cam[:persp]
    out[:how] = "#{cam[:how]}, fitted #{(fill * 100).round}%"
    out
  end

  # A ghost is the part's OWN material made translucent: a clone carrying
  # the same colour and texture, with alpha. Default-material faces (which
  # render in the style's front colour) clone that colour.
  def self.ghost_material(model, alpha, base = nil)
    key = base ? base.name : '(default)'
    nm = format('WR_CU_ghost_%02d %s', (alpha * 100).round, key)
    m = model.materials[nm]
    return m if m
    m = model.materials.add(nm)
    if base
      m.color = base.color
      if base.texture
        begin
          m.texture = base.texture.image_rep
          m.texture.size = [base.texture.width, base.texture.height]
        rescue StandardError
          nil
        end
      end
    else
      m.color = (model.rendering_options['FaceFrontColor'] rescue nil) || Sketchup::Color.new(255, 255, 255)
    end
    m.alpha = alpha
    m
  end

  # Ghosting: the piece is re-instanced inside a fresh empty group, flattened
  # there to raw faces, and every face painted translucent. Painting an
  # instance only reaches default-material faces, and WhisperRoom parts carry
  # their own colours, so flattening is the only way the ghost is uniform.
  #
  # NOT Entities#add_group(existing_entities): grouping entities that are not
  # in model.active_entities is a known way to crash SketchUp, and the staging
  # group is never the active context. An empty group filled with
  # add_instance is the safe form. All of it is on a STAGED copy and aborted.
  def self.ghost!(ctx, pcs, alpha, edges)
    model = ctx[:model]
    pcs.each do |pc|
      e = pc[:ent]
      next unless e.valid?
      if e.is_a?(Sketchup::Face)
        gm = ghost_material(model, alpha.to_f, e.material)
        e.material = gm
        e.back_material = gm
        next
      end
      next unless inst?(e)
      g = e.parent.entities.add_group
      begin
        ni = g.entities.add_instance(defn_of(e), e.transformation)
        ni.material = e.material if (e.material rescue nil)
      rescue StandardError => ex
        g.erase! if g.valid?
        ctx[:warnings] << "ghost: could not re-instance #{pc[:name]} (#{ex.class}); left solid"
        next
      end
      e.erase!
      FLATTEN_ROUNDS.times do
        nested = g.entities.select { |x| inst?(x) }
        break if nested.empty?
        nested.each { |x| x.explode if x.valid? }
      end
      g.entities.grep(Sketchup::Face).each do |f|
        gm = ghost_material(model, alpha.to_f, f.material)
        f.material = gm
        f.back_material = gm
      end
      g.entities.grep(Sketchup::Edge).each { |ed| ed.hidden = true } unless edges
      pc[:ent] = g
    end
  end

  # ================================================================= RENDER ==

  def self.aim(view, cam)
    c = view.camera
    c.set(p3(cam[:eye]), p3(cam[:target]), v3(cam[:up]))
    c.perspective = cam[:persp]
    c.aspect_ratio = cam[:w].to_f / cam[:h].to_f
    if cam[:persp]
      (c.fov_is_height = true) rescue nil
      c.fov = cam[:fov]
    else
      c.height = cam[:height]   # last: set() can reset the projection
    end
    view.refresh
  end

  def self.write(view, path, cam)
    view.write_image(:filename => path, :width => cam[:w], :height => cam[:h],
                     :antialias => true, :transparent => true)
  end

  # A red dot at every in-frame anchor, everything else hidden, section off.
  # Dots face the camera; their radius is anchor_dot_px in image pixels.
  def self.anchor_check!(ctx, cam, anchors_world, path, dot_px)
    s = ctx[:s]
    view = ctx[:model].active_view
    lv = ctx[:levels] || [s]
    shown = lv.flat_map { |g| g.entities.reject { |e| (e.hidden? rescue true) || lv.include?(e) } }
    shown.each { |e| (e.hidden = true) rescue nil }
    lv.each { |g| (g.entities.active_section_plane = nil) rescue nil }
    red = ctx[:model].materials['WR_CU_anchor'] || ctx[:model].materials.add('WR_CU_anchor')
    red.color = Sketchup::Color.new(255, 0, 0)
    d = s.entities.add_group
    anchors_world.each_value do |p|
      n = cam[:persp] ? vnorm(vsub(cam[:eye], p)) : vscale(cam[:fwd], -1.0)
      r = if cam[:persp]
            z = vdot(vsub(p, cam[:eye]), cam[:fwd])
            f = (cam[:h] / 2.0) / Math.tan(cam[:fov] * Math::PI / 360.0)
            dot_px.to_f * z / f
          else
            dot_px.to_f * cam[:height] / cam[:h].to_f
          end
      edges = d.entities.add_circle(p3(p), v3(n), r, 24)
      f = d.entities.add_face(edges)
      if f
        f.material = red
        f.back_material = red
      end
      d.entities.grep(Sketchup::Edge).each { |ed| ed.hidden = true }
    end
    aim(view, cam)
    ok = write(view, path, cam)
    d.erase! if d.valid?
    shown.each { |e| (e.hidden = false) rescue nil }
    ok
  end

  # ================================================================== SHOT ===

  def self.do_shot(run, sid, var)
    model = run[:model]
    spec = run[:spec]
    rig = spec['rig']
    shot = spec['shots'][sid] || {}
    pose = shot['pose'] || {}
    vpose = (pose['variants'] || {})[var] || {}
    file = "#{safe_name(sid)}_#{safe_name(var)}.png"
    rec = { 'shot' => sid, 'variant' => var, 'title' => shot['title'].to_s, 'file' => file,
            'status' => 'pending', 'warnings' => [], 'missing' => [], 'anchors' => {},
            'anchors_meta' => {}, 'anchors_missing' => [], 'parts' => [] }

    if vpose['blocked']
      rec['status'] = 'blocked'
      rec['reason'] = vpose['blocked'].to_s
      return rec
    end
    need = (pose['model'] || 'any').to_s
    unless need.downcase == 'any' || need.downcase == model.title.to_s.downcase
      rec['status'] = 'wrong-model'
      rec['reason'] = "needs \"#{need}\" open (this is \"#{model.title}\")"
      return rec
    end
    path = File.join(run[:out], file)
    if !run[:dry] && !run[:over] && File.exist?(path)
      rec['status'] = 'exists'
      rec['reason'] = 'file already there and Overwrite is off'
      return rec
    end

    p = merge_pose(pose['base'], vpose)
    w, h = Array(rig_value(rig, 'canvas', [2400, 1553])).map(&:to_i)
    ctx = { :model => model, :root => run[:root], :roots => run[:roots], :generated => [],
            :infile => run[:infile], :infile_index => run[:infile_index],
            :warnings => rec['warnings'], :loaded => [],
            :roles => {}, :index => run[:index], :w => w, :h => h }

    model.start_operation("WR close-up #{sid} #{var}", false)
    shade = nil
    sec_saved = nil
    layers0 = nil
    begin
      # Style, shading, section display and tag visibility are set INSIDE the
      # operation, so the abort takes them back too; they are also popped by
      # hand in the ensure, before the abort, in case one is not undoable.
      unless run[:dry]
        shade = WR_Shading.push(model, rig_value(rig, 'style', 'Style: Interior'), rig_value(rig, 'dark', 45))
        run[:stuck] |= WR_Shading.apply(model, rig_value(rig, 'dark', 45))
        sec_saved, s2 = push_section_ro(model)
        run[:stuck] |= s2
        layers0 = model.layers.map { |l| [l, (l.visible? rescue true)] }
        model.layers.each { |l| (l.visible = true) rescue nil }
        run[:style_used] = (model.styles.selected_style.name rescue '')
        run[:shading_lines] = WR_Shading.describe(model)
      end
      ctx[:s] = model.entities.add_group
      ctx[:s].name = 'WR_CU_STAGE'
      ctx[:outer] = ctx[:s]
      # CLIPS: one active section plane per entity context, so each extra
      # bounding plane gets its own nested group: outer -> clip 1 -> clip 2 ...
      # and parts are staged into the innermost level unless they name one
      # ("level": 0 = outside every clip). Planes are added before the render.
      ctx[:levels] = [ctx[:s]]
      Array(p['clips']).each_with_index do |_c, i|
        g = ctx[:levels].last.entities.add_group
        g.name = "WR_CU_CLIP#{i + 1}"
        ctx[:levels] << g
      end
      ctx[:s] = ctx[:levels].last
      (model.entities.active_section_plane = nil) rescue nil
      model.entities.each do |e|
        next if e == ctx[:outer]
        (e.hidden = true) rescue nil
      end

      # ---- stage
      (p['parts'] || []).each do |part|
        placed, how = stage_part(ctx, part)
        role = part['role'].to_s
        row = { 'role' => role, 'how' => how, 'optional' => !!part['optional'] }
        if placed.empty?
          desc = (part['sources'] || []).map { |s| s.reject { |k, _| k.start_with?('_') }.to_json }.join(' | ')
          if part['optional']
            rec['warnings'] << "optional part #{role} not found (#{desc})"
          else
            rec['missing'] << "#{role}: #{desc}"
          end
          rec['parts'] << row
          next
        end
        placed = split!(ctx, placed, part['split'], part['keep']) if part['split'].to_i > 0
        placed.each { |pc| pc[:box] = vis_box(pc[:ent], ident) if pc[:ent].valid? }
        ctx[:roles][role] = placed
        row['pieces'] = placed.select { |pc| inst?(pc[:ent]) }.map do |pc|
          b = pc[:box]
          sz = b ? (0..2).map { |i| (b[1][i] - b[0][i]).round(2) } : nil
          { 'name' => pc[:name], 'size_in' => sz }
        end
        row['loose_entities'] = placed.count { |pc| !inst?(pc[:ent]) }
        rec['parts'] << row
      end
      ctx[:index] = run[:index] = ctx[:index] || run[:index]
      rec['generated'] = ctx[:generated].uniq
      rec['flattened'] = flatten_materials!(model, run[:mats0], rig) unless run[:dry] || rig_value(rig, 'flat_style', true) == false
      unless rec['missing'].empty?
        rec['status'] = 'model-gap'
        rec['reason'] = 'MODEL GAP — part(s) not found; the shot is skipped, not drawn half-empty'
        return rec
      end

      # ---- moves (the explode)
      (p['moves'] || []).each do |mv|
        pcs = select(ctx, mv, mv.key?('index') ? mv['index'] : 'all')
        nested = pcs.reject { |it| it[:pc] }
        rec['warnings'] << "move skipped #{nested.length} nested piece(s); split deeper to move them" unless nested.empty?
        pcs = pcs.select { |it| it[:pc] }
        if pcs.empty?
          rec['warnings'] << "move matched nothing: #{mv.to_json}"
          next
        end
        if mv['rotate']
          rt = mv['rotate']
          about = rt['about'] ? point(ctx, rt['about']) : box_centre(box_union(pcs.map { |it| it[:box] }))
          if about.nil?
            rec['warnings'] << "rotate: about-point did not resolve: #{mv.to_json}"
            next
          end
          rtr = Geom::Transformation.rotation(p3(about), axis_vec(rt['axis'] || 'z'), rt['deg'].to_f * Math::PI / 180.0)
          pcs.group_by { |it| it[:ent].parent }.each { |par, its| par.entities.transform_entities(rtr, its.map { |it| it[:ent] }) }
          pcs.each { |it| it[:pc][:box] = vis_box(it[:pc][:ent], ident) }
          rec['moves'] = (rec['moves'] || []) << { 'pieces' => pcs.map { |it| it[:name] }, 'rotate' => rt }
          next unless mv['by'] || mv['away_from']
        end
        vec = if mv['by']
                mv['by'].map(&:to_f)
              elsif mv['away_from']
                ref = point(ctx, mv['away_from'])
                if ref.nil?
                  rec['warnings'] << "move away_from did not resolve: #{mv.to_json}"
                  next
                end
                c = box_centre(box_union(pcs.map { |it| it[:box] }))
                d = vsub(c, ref)
                d = [d[0], d[1], 0.0] unless mv['horizontal'] == false
                vscale(vnorm(d), (mv['dist'] || 3).to_f)
              end
        next if vec.nil?
        mtr = Geom::Transformation.translation(v3(vec))
        pcs.group_by { |it| it[:ent].parent }.each { |par, its| par.entities.transform_entities(mtr, its.map { |it| it[:ent] }) }
        pcs.each { |it| it[:pc][:box] = vis_box(it[:pc][:ent], ident) }
        rec['moves'] = (rec['moves'] || []) << { 'pieces' => pcs.map { |it| it[:name] }, 'by' => vec.map { |v| r3(v) } }
      end
      rec['explode'] = p.key?('explode') ? !!p['explode'] : !(p['moves'] || []).empty?

      # ---- bolts IN THEIR HOLES (after the explode, so they follow the part)
      (p['bolts'] || []).each { |bs| place_bolts!(ctx, rec, bs) }

      # ---- section axis, camera, anchors
      ctx[:sec] = section_geom(ctx, p['section'])
      rec['warnings'] << 'section selector matched nothing; rendered without a section' if p['section'] && ctx[:sec].nil?
      cam = build_camera(ctx, p, rig)
      ctx[:cam] = cam
      # Hides come before the anchors and the fit (they may rank by view, so
      # they need the first camera); the fit then frames what is SHOWN.
      (p['hide'] || []).each do |hd|
        pcs = select(ctx, hd, hd.key?('index') ? hd['index'] : 'all')
        rec['warnings'] << "hide matched nothing: #{hd.to_json}" if pcs.empty?
        pcs.each { |it| (it[:ent].hidden = true) rescue nil }
      end
      if fit_wanted?(p)
        cam = fit_camera!(ctx, cam, p)
        ctx[:cam] = cam
      end
      worlds = {}
      (p['anchors'] || {}).each do |nm, sp|
        info = {}
        pt = point(ctx, sp, info)
        if pt.nil?
          rec['anchors_missing'] << nm
          next
        end
        xy = project(pt, cam)
        inf = in_frame?(xy, w, h)
        rec['anchors'][nm] = xy ? [xy[0].round(1), xy[1].round(1)] : nil
        rec['anchors_meta'][nm] = { 'world' => pt.map { |v| r3(v) }, 'in_frame' => inf,
                                    'pieces' => info[:n].to_i, 'fallback' => !!info[:fallback] }
        worlds[nm] = pt if inf
      end

      # ---- ghosts (after anchors: ghosting flattens named children)
      (p['ghost'] || []).each do |gh|
        pcs = select(ctx, gh, gh.key?('index') ? gh['index'] : 'all').map { |it| it[:pc] }.compact
        if pcs.empty?
          rec['warnings'] << "ghost matched nothing: #{gh.to_json}"
          next
        end
        ghost!(ctx, pcs, (gh['alpha'] || 0.35), gh['edges'] != false)
      end

      # ---- section plane, oriented to face the camera
      sec_rec = nil
      if ctx[:sec]
        n = ctx[:sec][:axis]
        n = vscale(n, -1.0) if vdot(n, vsub(cam[:eye], ctx[:sec][:point])) < 0.0
        n = vscale(n, -1.0) if p['section']['flip']
        # Observed in the 2026-10-01 pilot: SketchUp keeps the side the plane's
        # normal points to. So the plane is given the normal pointing AWAY from
        # the camera, which removes the near half and shows the cut face.
        n = vscale(n, -1.0)
        sp = ctx[:s].entities.add_section_plane([p3(ctx[:sec][:point]), v3(n)])
        sp.activate
        sec_rec = { 'point' => ctx[:sec][:point].map { |v| r3(v) }, 'normal' => n.map { |v| r3(v) },
                    'flip' => !!p['section']['flip'], 'active' => (sp.active? rescue nil) }
      end
      rec['section'] = sec_rec
      # ---- clip planes: world point + normal; SketchUp keeps the side the
      # normal points to (observed), so "normal" names the side to KEEP.
      rec['clips'] = []
      Array(p['clips']).each_with_index do |c, i|
        lv = ctx[:levels][i]
        cp = lv.entities.add_section_plane([p3(c['point']), v3(c['keep'] || c['normal'])])
        cp.activate
        rec['clips'] << { 'level' => i, 'point' => c['point'], 'keep' => (c['keep'] || c['normal']), 'active' => (cp.active? rescue nil) }
      end

      # ---- what the subject spans, against the frame
      all = box_union(ctx[:roles].values.flatten.select { |pc| pc[:ent].valid? && !(pc[:ent].hidden? rescue false) }
                                 .map { |pc| vis_box(pc[:ent], ident) }.compact)
      if all[0][0].finite?
        corners = [[0, 0, 0], [1, 1, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1], [0, 1, 1]]
                  .map { |m| [all[m[0]][0], all[m[1]][1], all[m[2]][2]] }
        outside = corners.map { |q| project(q, cam) }.count { |xy| !in_frame?(xy, w, h) }
        rec['subject_box_in'] = (0..2).map { |i| (all[1][i] - all[0][i]).round(2) }
        rec['subject_corners_outside'] = outside
      end

      rec['w'] = w
      rec['h'] = h
      rec['in_per_px'] = cam[:persp] ? nil : r3(cam[:height] / h.to_f * 1000.0) / 1000.0
      rec['camera'] = { 'eye' => cam[:eye].map { |v| r3(v) }, 'target' => cam[:target].map { |v| r3(v) },
                        'up' => cam[:up].map { |v| r3(v) }, 'persp' => cam[:persp],
                        'height' => cam[:persp] ? nil : r3(cam[:height]),
                        'fov' => cam[:persp] ? cam[:fov] : nil,
                        'azimuth' => r3(cam[:azim]), 'elevation' => r3(cam[:elev]), 'how' => cam[:how] }

      if run[:dry]
        rec['status'] = 'dry-ok'
        return rec
      end

      # ---- render
      view = model.active_view
      aim(view, cam)
      Sketchup.status_text = "Close-up #{sid} #{var}"
      ok = write(view, path, cam)
      unless ok
        rec['status'] = 'failed'
        rec['reason'] = "write_image returned false for #{path}"
        return rec
      end
      run[:written] << path
      if run[:check] && !worlds.empty?
        cdir = File.join(run[:out], '_anchorcheck')
        FileUtils.mkdir_p(cdir)
        cpath = File.join(cdir, file)
        rec['anchor_check'] = anchor_check!(ctx, cam, worlds, cpath, rig_value(rig, 'anchor_dot_px', 5)) ? "_anchorcheck/#{file}" : 'FAILED'
      end
      rec['status'] = rec['anchors_missing'].empty? && rec['warnings'].empty? ? 'rendered' : 'rendered-with-warnings'
      rec
    rescue StandardError => e
      rec['status'] = 'error'
      rec['reason'] = "#{e.class}: #{e.message}"
      rec['backtrace'] = (e.backtrace || []).first(4)
      rec
    ensure
      (layers0 || []).each { |l, v| (l.visible = v) rescue nil }
      pop_section_ro(model, sec_saved) if sec_saved
      WR_Shading.pop(model, shade) if shade
      model.abort_operation
      run[:loaded].concat(ctx[:loaded])
    end
  end

  # ================================================================= THE RUN ==

  # Definitions a shot loaded that outlived its abort: removed again, newest
  # first, only if nothing uses them and they were not in the model before.
  def self.cleanup_defs(model, before_ids)
    gone = []
    # One pass per nesting level: a child only loses its last instance when
    # its parent goes. Assembled booths nest ten and more deep.
    40.times do
      extra = model.definitions.to_a.reject { |d| before_ids.include?(d.persistent_id) }
      extra = extra.select { |d| d.instances.empty? }
      break if extra.empty?
      model.start_operation('WR close-up cleanup', true)
      extra.each do |d|
        nm = d.name
        gone << nm if (model.definitions.remove(d) rescue false)
      end
      model.commit_operation
    end
    gone
  rescue StandardError => e
    ["cleanup failed: #{e.class}: #{e.message}"]
  end

  # Every in_file a picked shot names, loaded once before the shots and
  # OUTSIDE every operation (an aborted load would take the definition with
  # it). They place no instance, so cleanup_defs removes them at the end.
  def self.preload_files(run, poses, jobs)
    want = []
    scan = lambda do |o|
      case o
      when Hash
        want << o['in_file'].to_s if o['in_file']
        o.each { |k, v| scan.call(v) unless k.to_s.start_with?('_') }
      when Array then o.each { |v| scan.call(v) }
      end
    end
    jobs.each do |sid, var|
      pz = poses[sid] || {}
      scan.call(merge_pose(pz['base'], (pz['variants'] || {})[var]))
    end
    want.uniq.each do |f|
      path = f
      unless path =~ /\A[A-Za-z]:[\\\/]/
        path = run[:roots].map { |r| File.join(r, f) }.find { |c| File.exist?(c) } || f
      end
      d = File.exist?(path) ? (run[:model].definitions.load(path) rescue nil) : nil
      run[:infile][f] = d if d
      puts "  preload #{f}: #{d ? d.name : 'FAILED'}"
    end
  end

  # Materials a file load brought in that outlived the aborts: removed again
  # when nothing in the model uses them and they were not there before.
  def self.cleanup_materials(model, before_names)
    extra = model.materials.to_a.reject { |m| before_names.include?(m.name) }
    return [] if extra.empty?
    used = {}
    model.definitions.each do |d|
      d.entities.each do |e|
        used[e.material] = true if e.respond_to?(:material) && e.material
        used[e.back_material] = true if e.is_a?(Sketchup::Face) && e.back_material
      end
    end
    model.entities.each { |e| used[e.material] = true if e.respond_to?(:material) && e.material }
    gone = []
    model.start_operation('WR close-up material cleanup', true)
    extra.each do |m|
      next if used[m]
      nm = m.name
      gone << "material #{nm}" if (model.materials.remove(m) rescue false)
    end
    model.commit_operation
    gone
  rescue StandardError => e
    ["material cleanup failed: #{e.class}: #{e.message}"]
  end

  # run(opts) — no dialogs; returns a summary hash (the bridge returns it as
  # JSON). opts: shots ('pilot' | 'all' | 'CU-03,CU-06:seated'), dry (bool),
  # out (folder), over (bool), check (bool, anchor-check pass), recover
  # (bool), spec (path).
  def self.run(opts = {})
    load_shading
    model = Sketchup.active_model
    spec = load_spec(opts['spec'])
    rig = spec['rig'] || {}
    poses = {}
    spec['shots'].each { |id, s| poses[id] = s['pose'] if s['pose'] }
    jobs, miss = pick_shots(poses, opts['shots'] || 'pilot')
    dry = opts.key?('dry') ? !!opts['dry'] : true
    out = (opts['out'] || rig_value(rig, 'out_dir', DEF_OUT)).to_s.tr('\\', '/')
    run = { :model => model, :spec => spec, :dry => dry, :out => out,
            :over => !!opts['over'], :check => opts.key?('check') ? !!opts['check'] : true,
            :root => (opts['component_root'] || rig_value(rig, 'component_root', 'Z:/Sketchup/NewMasterComponentList')).to_s,
            :roots => ([opts['component_root'] || rig_value(rig, 'component_root', 'Z:/Sketchup/NewMasterComponentList')] +
                       Array(rig_value(rig, 'component_fallback_roots', []))).map(&:to_s).uniq,
            :index => nil, :written => [], :loaded => [], :stuck => [],
            :style_used => nil, :shading_lines => [] }
    FileUtils.mkdir_p(out)

    fp0 = fingerprint(model)
    defs0 = model.definitions.map(&:persistent_id)
    mats0 = model.materials.map(&:name)
    run[:mats0] = mats0
    closed = close_contexts(model)
    run[:infile] = {}
    run[:infile_index] = {}
    preload_files(run, poses, jobs)
    view = model.active_view
    cam0 = save_camera(view)
    results = []
    started = Time.now
    begin
      jobs.each do |sid, var|
        results << do_shot(run, sid, var)
      end
    ensure
      restore_camera(view, cam0)
      Sketchup.status_text = ''
    end
    stuck = run[:stuck]
    style_used = run[:style_used]
    shading_lines = run[:shading_lines]

    removed = cleanup_defs(model, defs0)
    removed += cleanup_materials(model, mats0)
    recovered = nil
    if !dry && !run[:written].empty? && rig_value(rig, 'recover', true) && opts['recover'] != false
      recovered = WR_Shading.recover(out)
      cdir = File.join(out, '_anchorcheck')
      WR_Shading.recover(cdir) if File.directory?(cdir)
    end
    fp1 = fingerprint(model)
    diffs = fp_diff(fp0, fp1)

    meta = { 'model' => model.title.to_s, 'model_path' => model.path.to_s, 'sketchup' => Sketchup.version.to_s,
             'rig_version' => RIG_VERSION, 'spec' => spec['_path'], 'spec_source' => spec['source'],
             'generated_at' => Time.now.utc.strftime('%Y-%m-%dT%H:%M:%SZ'),
             'style' => (dry ? nil : style_used), 'dark' => rig_value(rig, 'dark', 45),
             'ao' => false }
    rows_written = dry ? nil : write_json(out, results, meta)
    diag = write_diagnostics(out, run, results, meta, fp0, diffs, removed, closed, stuck,
                             (dry ? [] : shading_lines), miss, recovered, Time.now - started)
    print_summary(run, results, diffs, removed, diag, miss)

    { 'mode' => dry ? 'dry' : 'render', 'model' => model.title.to_s, 'out' => out,
      'shots' => results.map do |r|
        { 'shot' => r['shot'], 'variant' => r['variant'], 'status' => r['status'], 'file' => r['file'],
          'reason' => r['reason'], 'missing' => r['missing'], 'anchors' => r['anchors'],
          'anchors_missing' => r['anchors_missing'], 'warnings' => r['warnings'], 'generated' => r['generated'],
          'parts' => r['parts'], 'subject_corners_outside' => r['subject_corners_outside'] }
      end,
      'unmatched_tokens' => miss, 'restored' => diffs.empty?, 'restore_diffs' => diffs,
      'definitions_removed' => removed, 'contexts_closed' => closed, 'shading_stuck' => stuck,
      'json_rows' => rows_written, 'diagnostics' => diag }
  end

  # _closeups.json: one row per image, merged with what the folder already
  # holds (keyed by file), so two passes in two models fill one file.
  def self.write_json(out, results, meta)
    path = File.join(out, '_closeups.json')
    rows = {}
    if File.exist?(path)
      begin
        old = JSON.parse(File.read(path, :encoding => 'UTF-8'))
        Array(old['images']).each { |r| rows[r['file']] = r }
      rescue StandardError
        File.rename(path, path + ".unreadable-#{Time.now.strftime('%Y%m%d%H%M%S')}") rescue nil
      end
    end
    results.each do |r|
      next unless r['status'].to_s.start_with?('rendered')
      rows[r['file']] = {
        'file' => r['file'], 'shot' => r['shot'], 'variant' => r['variant'], 'title' => r['title'],
        'w' => r['w'], 'h' => r['h'], 'in_per_px' => r['in_per_px'], 'camera' => r['camera'],
        'section' => r['section'], 'explode' => r['explode'], 'anchors' => r['anchors'],
        'anchors_meta' => r['anchors_meta'], 'anchors_missing' => r['anchors_missing'],
        'missing' => r['missing'], 'warnings' => r['warnings'], 'anchor_check' => r['anchor_check'],
        'generated' => r['generated'] || [], 'parts' => r['parts'], 'moves' => r['moves'],
        'subject_corners_outside' => r['subject_corners_outside'],
        'model' => meta['model'], 'model_path' => meta['model_path'], 'sketchup' => meta['sketchup'],
        'style' => meta['style'], 'dark' => meta['dark'], 'ao' => meta['ao'],
        'rig_version' => meta['rig_version'], 'generated_at' => meta['generated_at']
      }
    end
    doc = { 'version' => 1, 'note' => 'Written by scripts/am-closeup-export.rb. Anchors are image pixels, ' \
                                       'origin top-left, y down. Labels are drawn by the app.',
            'images' => rows.values.sort_by { |r| [r['shot'].to_s, r['variant'].to_s] } }
    File.open(path, 'w:UTF-8') { |f| f.write(JSON.pretty_generate(doc)) }
    rows.length
  rescue StandardError => e
    puts "  (could not write _closeups.json: #{e.class}: #{e.message})"
    nil
  end

  def self.write_diagnostics(out, run, results, meta, fp0, diffs, removed, closed, stuck, shading, miss, recovered, secs)
    path = File.join(out, '_diagnostics.txt')
    File.open(path, 'a:UTF-8') do |f|
      f.puts '=' * 78
      f.puts "ASSEMBLY CLOSE-UPS — #{run[:dry] ? 'DRY RUN' : 'RENDER'}   #{meta['generated_at']}"
      f.puts "model        #{meta['model']}   (#{meta['model_path']})"
      f.puts "sketchup     #{meta['sketchup']}   rig #{meta['rig_version']}"
      f.puts "spec         #{meta['spec']}"
      f.puts "spec source  #{meta['spec_source'].to_json}"
      f.puts "out          #{run[:out]}   overwrite #{run[:over]}   anchor check #{run[:check]}"
      f.puts "components   #{run[:roots].join('  then  ')}"
      f.puts "contexts closed on entry: #{closed}"
      f.puts format('elapsed      %.1f s', secs.to_f)
      f.puts "unmatched shot tokens: #{miss.join(', ')}" unless miss.empty?
      unless shading.empty?
        f.puts ''
        f.puts 'SHADING CONTRACT AS RENDERED (diff against the Iso30 DoorCombos block)'
        shading.each { |l| f.puts "  #{l}" }
        f.puts "  ao                   #{meta['ao']}"
      end
      unless stuck.empty?
        f.puts '  KEYS THAT WOULD NOT TAKE:'
        stuck.each { |s| f.puts "    #{s}" }
      end
      results.each do |r|
        f.puts ''
        f.puts "#{r['shot']} #{r['variant']} — #{r['status'].upcase}   #{r['file']}"
        f.puts "  #{r['title']}"
        f.puts "  reason: #{r['reason']}" if r['reason']
        r['missing'].each { |m| f.puts "  MODEL GAP  #{m}" }
        r['parts'].each do |pt|
          f.puts "  part #{pt['role']}#{pt['optional'] ? ' (optional)' : ''}: #{pt['how'] || 'NOT FOUND'}"
          Array(pt['pieces']).each do |pc|
            sz = pc['size_in'] ? pc['size_in'].map { |v| format('%.2f', v) }.join(' x ') : '?'
            f.puts "      piece  #{pc['name']}   #{sz} in"
          end
          f.puts "      + #{pt['loose_entities']} loose edge/face entities" if pt['loose_entities'].to_i > 0
        end
        if r['camera']
          c = r['camera']
          f.puts "  camera #{c['persp'] ? 'PERSPECTIVE fov ' + c['fov'].to_s : 'parallel, view height ' + c['height'].to_s + ' in'}" \
                 "  azimuth #{c['azimuth']} elev #{c['elevation']} (#{c['how']})"
          f.puts "         target #{c['target'].inspect}  eye #{c['eye'].inspect}"
          f.puts "  canvas #{r['w']} x #{r['h']}  #{r['in_per_px'] ? format('%.5f in/px', r['in_per_px']) : ''}"
        end
        f.puts "  subject #{r['subject_box_in'].inspect} in; #{r['subject_corners_outside']} of 8 box corners outside the frame" if r['subject_box_in']
        f.puts "  section #{r['section'].inspect}" if r['section']
        f.puts "  explode #{r['explode']}" unless r['explode'].nil?
        r['anchors'].each do |nm, xy|
          m = r['anchors_meta'][nm] || {}
          f.puts format('  anchor %-16s px %-18s world %s%s%s', nm, xy.inspect, m['world'].inspect,
                        m['in_frame'] ? '' : '  OUTSIDE THE FRAME', m['fallback'] ? '  (fallback)' : '')
        end
        r['anchors_missing'].each { |nm| f.puts "  anchor #{nm} DID NOT RESOLVE — no pixel written" }
        r['warnings'].each { |w| f.puts "  warning: #{w}" }
        f.puts "  anchor check: #{r['anchor_check']}" if r['anchor_check']
        Array(r['backtrace']).each { |b| f.puts "    at #{b}" }
      end
      f.puts ''
      f.puts "brightness recovery: #{recovered.inspect}" unless recovered.nil?
      f.puts "loaded definitions removed again after the aborts: #{removed.join(', ')}" unless removed.empty?
      f.puts 'RESTORE CHECK (fingerprint before vs after the run)'
      if diffs.empty?
        f.puts '  identical — entities, hidden flags, definitions, materials, tags, scenes, style,'
        f.puts '  rendering and shadow keys, section, camera, modified flag'
      else
        diffs.each { |d| f.puts "  *** #{d}" }
      end
    end
    path
  rescue StandardError => e
    puts "  (could not write _diagnostics.txt: #{e.class}: #{e.message})"
    nil
  end

  def self.print_summary(run, results, diffs, removed, diag, miss)
    puts ''
    puts "ASSEMBLY CLOSE-UPS #{run[:dry] ? '(DRY RUN — nothing rendered)' : ''}"
    results.each do |r|
      puts format('  %-6s %-10s %-24s %s', r['shot'], r['variant'], r['status'], r['reason'].to_s)
      r['missing'].each { |m| puts "           MODEL GAP #{m}" }
      puts "           anchors not resolved: #{r['anchors_missing'].join(', ')}" unless r['anchors_missing'].empty?
      r['warnings'].each { |w| puts "           warning: #{w}" }
    end
    puts "  shot tokens that matched nothing: #{miss.join(', ')}" unless miss.empty?
    puts "  definitions removed after abort: #{removed.length}" unless removed.empty?
    puts diffs.empty? ? '  model restored: fingerprint identical' : "  *** model NOT identical: #{diffs.join('; ')}"
    puts "  diagnostics: #{diag}"
  end

  # survey('duct box') — every definition whose name matches, with its size,
  # how many instances the model holds (nested included) and where the first
  # few sit. For turning a MODEL GAP into a working pose.
  def self.survey(pattern, limit = 40)
    model = Sketchup.active_model
    re = rx(pattern)
    idx, = instance_index(model, nil)
    by = Hash.new { |hh, k| hh[k] = [] }
    idx.each { |it| by[it[:ent].respond_to?(:definition) ? (it[:ent].definition rescue nil) : nil] << it }
    out = []
    model.definitions.each do |d|
      next if d.image?
      next unless name_hit?(re, d.name)
      b = d.bounds
      its = by[d]
      out << { 'definition' => d.name, 'size_in' => [b.width, b.height, b.depth].map { |v| v.to_f.round(2) },
               'instances' => its.length,
               'examples' => its.first(3).map do |it|
                 { 'origin' => arr(it[:tr].origin).map { |v| v.round(2) },
                   'path' => it[:path].join(' > ') }
               end }
      break if out.length >= limit
    end
    out.each do |r|
      puts format('  %-50s %-26s x%d', r['definition'], r['size_in'].inspect, r['instances'])
      r['examples'].each { |e| puts "      at #{e['origin'].inspect} in #{e['path'].empty? ? 'top level' : e['path']}" }
    end
    out
  end

  # ------------------------------------------------------------- the panel --

  def self.run_ui
    keys = %w[shots dry out over check recover]
    prompts = ['Shots — pilot / all / CU-03,CU-06:seated',
               'Dry run — resolve names and cameras only',
               'Output folder',
               'Overwrite files already there',
               'Anchor check images (red dots)',
               'Recover brightness after export']
    defaults = { 'shots' => 'pilot', 'dry' => 'Yes', 'out' => DEF_OUT, 'over' => 'No',
                 'check' => 'Yes', 'recover' => 'Yes' }
    vals = keys.map do |k|
      v = Sketchup.read_default(PREF, k, defaults[k]).to_s
      v.empty? ? defaults[k] : v
    end
    lists = ['', 'Yes|No', '', 'No|Yes', 'Yes|No', 'Yes|No']
    res = UI.inputbox(prompts, vals, lists, 'Assembly close-ups')
    return unless res
    cfg = {}
    keys.each_with_index { |k, i| cfg[k] = res[i].to_s.strip }
    keys.each { |k| Sketchup.write_default(PREF, k, cfg[k]) }
    s = run('shots' => cfg['shots'], 'dry' => cfg['dry'] == 'Yes', 'out' => cfg['out'],
            'over' => cfg['over'] == 'Yes', 'check' => cfg['check'] == 'Yes',
            'recover' => cfg['recover'] == 'Yes')
    lines = s['shots'].map { |r| "#{r['shot']} #{r['variant']}: #{r['status']}" }
    UI.messagebox("Assembly close-ups (#{s['mode']})\n\n#{lines.join("\n")}\n\n" \
                  "#{s['restored'] ? 'Model restored exactly.' : 'MODEL NOT IDENTICAL — see the diagnostics.'}\n" \
                  "#{s['diagnostics']}")
  rescue StandardError => e
    UI.messagebox("Assembly close-ups failed:\n\n#{e.class}: #{e.message}")
    puts "FAILED: #{e.class}: #{e.message}"
    puts e.backtrace.first(5)
  end
end

WR_AmCloseups.run_ui unless $wr_no_autorun || $wr_suppress_autorun
