# @title Build Booth MDL 84126 S
# GENERATED by scripts/gen-booth.py — regenerate, don't hand-edit.
#
# MDL 84126 S  ("Sound Booth · 7'×10.5'")
#   exterior  128.0" x 86.0"      interior 124.0" x 82.0"
#   panels    1" thick, 81" tall, separated by the 2" mid-wall seam-seal stem
#   run rule  interior = sum(panels) + 2" per joint
#
# Panel kinds are interchangeable — the door frame, vent, cable and window walls
# all swap into any position. What's drawn here is one arrangement, not a rule.

module WR_BOOTH_84126_S
  W = 128.0
  H = 86.0
  T = 2.0
  PH = 81.0

  PARTS = [
    { :k=>'panel', :id=>'N0', :side=>'N', :sk=>'VNT', :pack=>nil, :x=>2.0, :y=>84.0, :dx=>38.71, :dy=>1.0 },
    { :k=>'seal', :id=>'N-seal0', :side=>'N', :sk=>'SEAL', :pack=>'Std mid-wall seam seal', :x=>40.71, :y=>84.0, :dx=>2.0, :dy=>1.0 },
    { :k=>'panel', :id=>'N1', :side=>'N', :sk=>'VNT', :pack=>nil, :x=>42.71, :y=>84.0, :dx=>38.71, :dy=>1.0 },
    { :k=>'seal', :id=>'N-seal1', :side=>'N', :sk=>'SEAL', :pack=>'Std mid-wall seam seal', :x=>81.42, :y=>84.0, :dx=>2.0, :dy=>1.0 },
    { :k=>'panel', :id=>'N2', :side=>'N', :sk=>'VNT', :pack=>nil, :x=>83.42, :y=>84.0, :dx=>42.581, :dy=>1.0 },
    { :k=>'panel', :id=>'S0', :side=>'S', :sk=>'SOLID', :pack=>nil, :x=>2.0, :y=>1.0, :dx=>38.71, :dy=>1.0 },
    { :k=>'seal', :id=>'S-seal0', :side=>'S', :sk=>'SEAL', :pack=>'Std mid-wall seam seal', :x=>40.71, :y=>1.0, :dx=>2.0, :dy=>1.0 },
    { :k=>'panel', :id=>'S1', :side=>'S', :sk=>'DRFRM', :pack=>nil, :x=>42.71, :y=>1.0, :dx=>38.71, :dy=>1.0 },
    { :k=>'seal', :id=>'S-seal1', :side=>'S', :sk=>'SEAL', :pack=>'Std mid-wall seam seal', :x=>81.42, :y=>1.0, :dx=>2.0, :dy=>1.0 },
    { :k=>'panel', :id=>'S2', :side=>'S', :sk=>'SOLID', :pack=>nil, :x=>83.42, :y=>1.0, :dx=>42.581, :dy=>1.0 },
    { :k=>'panel', :id=>'E0', :side=>'E', :sk=>'VNT', :pack=>nil, :x=>126.0, :y=>2.0, :dx=>1.0, :dy=>39.024 },
    { :k=>'seal', :id=>'E-seal0', :side=>'E', :sk=>'SEAL', :pack=>'Std mid-wall seam seal', :x=>126.0, :y=>41.024, :dx=>1.0, :dy=>2.0 },
    { :k=>'panel', :id=>'E1', :side=>'E', :sk=>'SOLID', :pack=>nil, :x=>126.0, :y=>43.024, :dx=>1.0, :dy=>40.976 },
    { :k=>'panel', :id=>'W0', :side=>'W', :sk=>'SOLID', :pack=>nil, :x=>1.0, :y=>2.0, :dx=>1.0, :dy=>39.024 },
    { :k=>'seal', :id=>'W-seal0', :side=>'W', :sk=>'SEAL', :pack=>'Std mid-wall seam seal', :x=>1.0, :y=>41.024, :dx=>1.0, :dy=>2.0 },
    { :k=>'panel', :id=>'W1', :side=>'W', :sk=>'SOLID', :pack=>nil, :x=>1.0, :y=>43.024, :dx=>1.0, :dy=>40.976 }
  ]

  def self.pt(x, y, z = 0.0); Geom::Point3d.new(x, y, z); end

  def self.build
    model = Sketchup.active_model
    begin
      model.options["UnitsOptions"]["LengthFormat"] = Length::Architectural
    rescue StandardError
    end
    model.start_operation("Build MDL 84126 S", true)

    tag = lambda do |name, rgb|
      l = model.layers[name] || model.layers.add(name)
      (l.color = Sketchup::Color.new(*rgb)) rescue nil
      l
    end
    t_wall = tag.call("WR-Booth-Walls", [120, 128, 140])
    t_door = tag.call("WR-Booth-Door",  [238,  98,  22])
    t_vent = tag.call("WR-Booth-Vent",  [ 64, 102, 124])
    t_seal = tag.call("WR-Booth-Seals", [ 90,  90,  96])
    t_flr  = tag.call("WR-Booth-Floor", [210, 210, 210])

    booth = model.entities.add_group
    booth.name = "MDL 84126 S"

    f = booth.entities.add_group
    fc = f.entities.add_face([pt(0,0), pt(W,0), pt(W,H), pt(0,H)])
    fc.reverse! if fc && fc.normal.z < 0
    f.name = "floor"; f.layer = t_flr

    PARTS.each do |p|
      g = booth.entities.add_group
      face = g.entities.add_face([ pt(p[:x], p[:y]),
                                   pt(p[:x] + p[:dx], p[:y]),
                                   pt(p[:x] + p[:dx], p[:y] + p[:dy]),
                                   pt(p[:x], p[:y] + p[:dy]) ])
      next if face.nil?
      face.reverse! if face.normal.z < 0
      face.pushpull(PH)
      g.name  = p[:pack] ? "#{p[:id]}  #{p[:pack]}" : "#{p[:id]}  #{p[:sk]}"
      g.layer = if p[:k] == "seal" then t_seal
                elsif p[:sk] == "DRFRM" then t_door
                elsif p[:sk] == "VNT"   then t_vent
                else t_wall
                end
    end

    model.commit_operation
    model.active_view.zoom_extents

    puts ""
    puts "MDL 84126 S built."
    puts "  exterior 128.0\" x 86.0\"   interior 124.0\" x 82.0\""
    puts "  10 wall panels + 6 mid-wall seam seals, panels 1\" x 81\" tall"
    puts "  packing list lists 10 wall panels — agrees"
    puts "  NOTE: N wall [40, 40, 44] -> [38.71, 38.71, 42.581] (scaled), + 2 seal(s) = 124.00' run"
    puts "  NOTE: S wall [40, 40, 44] -> [38.71, 38.71, 42.581] (scaled), + 2 seal(s) = 124.00' run"
    puts "  NOTE: E wall [40, 42] -> [39.024, 40.976] (scaled), + 1 seal(s) = 82.00' run"
    puts "  NOTE: W wall [40, 42] -> [39.024, 40.976] (scaled), + 1 seal(s) = 82.00' run"
    puts "  Corner seam seals are NOT modelled yet — no dimensioned corner detail."
    puts ""
  rescue StandardError => e
    model.abort_operation if model
    puts "FAILED: #{e.class}: #{e.message}"
    puts e.backtrace.first(5)
  end
end

WR_BOOTH_84126_S.build
