# @title Build Booth MDL 4872 S
# GENERATED by scripts/gen-booth.py — do not hand-edit; regenerate instead.
#
# MDL 4872 S  ("Sound Booth · 4'×6'")
#   exterior      74.0" x 50.0"      wall thickness 2.0"
#   interior      70" x 46"
#   wall panels   6 placed
#   panel height  82.5" (STD wall component L)
#
# Panels are massing boxes at true slot positions — correct sizes, positions and
# names, not the real interlocking geometry. Good for layout, plans and fit.

module WR_BOOTH_4872_S
  W  = 74.0
  H  = 50.0
  T  = 2.0
  PH = 82.5

  PANELS = [
    { :id=>'N0', :side=>'N', :kind=>'VNT', :pack=>nil, :x=>2.0, :y=>48.0, :dx=>46.0, :dy=>2.0 },
    { :id=>'N1', :side=>'N', :kind=>'SOLID', :pack=>nil, :x=>48.0, :y=>48.0, :dx=>24.0, :dy=>2.0 },
    { :id=>'S0', :side=>'S', :kind=>'DRFRM', :pack=>nil, :x=>2.0, :y=>0.0, :dx=>46.0, :dy=>2.0 },
    { :id=>'S1', :side=>'S', :kind=>'SOLID', :pack=>nil, :x=>48.0, :y=>0.0, :dx=>24.0, :dy=>2.0 },
    { :id=>'E0', :side=>'E', :kind=>'SOLID', :pack=>nil, :x=>72.0, :y=>2.0, :dx=>2.0, :dy=>46.0 },
    { :id=>'W0', :side=>'W', :kind=>'SOLID', :pack=>nil, :x=>0.0, :y=>2.0, :dx=>2.0, :dy=>46.0 }
  ]

  def self.pt(x, y, z = 0.0); Geom::Point3d.new(x, y, z); end

  def self.build
    model = Sketchup.active_model
    begin
      o = model.options["UnitsOptions"]
      o["LengthFormat"] = Length::Architectural
    rescue StandardError
    end
    model.start_operation("Build MDL 4872 S", true)

    tag = lambda do |name, rgb|
      l = model.layers[name] || model.layers.add(name)
      l.color = Sketchup::Color.new(*rgb) rescue nil
      l
    end
    t_wall = tag.call("WR-Booth-Walls", [120, 128, 140])
    t_door = tag.call("WR-Booth-Door",  [238,  98,  22])
    t_vent = tag.call("WR-Booth-Vent",  [ 64, 102, 124])
    t_flr  = tag.call("WR-Booth-Floor", [210, 210, 210])

    booth = model.entities.add_group
    booth.name = "MDL 4872 S"

    f = booth.entities.add_group
    face = f.entities.add_face([pt(0,0), pt(W,0), pt(W,H), pt(0,H)])
    face.reverse! if face && face.normal.z < 0
    f.name = "floor"; f.layer = t_flr

    PANELS.each do |p|
      g = booth.entities.add_group
      fc = g.entities.add_face([ pt(p[:x], p[:y]),
                                 pt(p[:x] + p[:dx], p[:y]),
                                 pt(p[:x] + p[:dx], p[:y] + p[:dy]),
                                 pt(p[:x], p[:y] + p[:dy]) ])
      next if fc.nil?
      fc.reverse! if fc.normal.z < 0
      fc.pushpull(PH)
      g.name  = "#{p[:id]}  #{p[:pack] || p[:kind]}"
      g.layer = case p[:kind]
                when "DRFRM" then t_door
                when "VNT"   then t_vent
                else              t_wall
                end
    end

    model.commit_operation
    model.active_view.zoom_extents

    puts ""
    puts "MDL 4872 S built."
    puts "  exterior 74.0\" x 50.0\"   interior 70\" x 46\"   wall 2.0\""
    puts "  #{PANELS.size} wall panels placed, each #{PH}\" tall"
    puts "  packing list for this model lists 6 wall panels — agrees"
    # none
    puts "  Massing boxes — correct sizes and positions, not real interlocking geometry."
    puts ""
  rescue StandardError => e
    model.abort_operation if model
    puts "FAILED: #{e.class}: #{e.message}"
    puts e.backtrace.first(5)
  end
end

WR_BOOTH_4872_S.build
