# @title Build Booth MDL 9696 E
# GENERATED by scripts/gen-booth.py — regenerate, don't hand-edit.
#
# MDL 9696 E  ("Sound Booth · 8'×8'")
#   exterior  98.0" x 98.0"      interior 89.5" x 89.5"
#   panels    1" thick, 81" tall, separated by the 2" mid-wall seam-seal stem
#   run rule  interior = sum(panels) + 2" per joint
#
# Panel kinds are interchangeable — the door frame, vent, cable and window walls
# all swap into any position. What's drawn here is one arrangement, not a rule.

module WR_BOOTH_9696_E
  W = 98.0
  H = 98.0
  T = 4.25
  PH = 81.0

  PARTS = [
    { :k=>'panel', :id=>'N0', :side=>'N', :sk=>'VNT', :pack=>nil, :x=>4.25, :y=>93.75, :dx=>43.75, :dy=>1.0 },
    { :k=>'seal', :id=>'N-seal0', :side=>'N', :sk=>'SEAL', :pack=>'Std mid-wall seam seal', :x=>48.0, :y=>93.75, :dx=>2.0, :dy=>1.0 },
    { :k=>'panel', :id=>'N1', :side=>'N', :sk=>'VNT', :pack=>nil, :x=>50.0, :y=>93.75, :dx=>43.75, :dy=>1.0 },
    { :k=>'panel', :id=>'S0', :side=>'S', :sk=>'DRFRM', :pack=>nil, :x=>4.25, :y=>3.25, :dx=>43.75, :dy=>1.0 },
    { :k=>'seal', :id=>'S-seal0', :side=>'S', :sk=>'SEAL', :pack=>'Std mid-wall seam seal', :x=>48.0, :y=>3.25, :dx=>2.0, :dy=>1.0 },
    { :k=>'panel', :id=>'S1', :side=>'S', :sk=>'SOLID', :pack=>nil, :x=>50.0, :y=>3.25, :dx=>43.75, :dy=>1.0 },
    { :k=>'panel', :id=>'E0', :side=>'E', :sk=>'VNT', :pack=>nil, :x=>93.75, :y=>4.25, :dx=>1.0, :dy=>43.75 },
    { :k=>'seal', :id=>'E-seal0', :side=>'E', :sk=>'SEAL', :pack=>'Std mid-wall seam seal', :x=>93.75, :y=>48.0, :dx=>1.0, :dy=>2.0 },
    { :k=>'panel', :id=>'E1', :side=>'E', :sk=>'SOLID', :pack=>nil, :x=>93.75, :y=>50.0, :dx=>1.0, :dy=>43.75 },
    { :k=>'panel', :id=>'W0', :side=>'W', :sk=>'SOLID', :pack=>nil, :x=>3.25, :y=>4.25, :dx=>1.0, :dy=>43.75 },
    { :k=>'seal', :id=>'W-seal0', :side=>'W', :sk=>'SEAL', :pack=>'Std mid-wall seam seal', :x=>3.25, :y=>48.0, :dx=>1.0, :dy=>2.0 },
    { :k=>'panel', :id=>'W1', :side=>'W', :sk=>'SOLID', :pack=>nil, :x=>3.25, :y=>50.0, :dx=>1.0, :dy=>43.75 }
  ]

  def self.pt(x, y, z = 0.0); Geom::Point3d.new(x, y, z); end

  def self.build
    model = Sketchup.active_model
    begin
      model.options["UnitsOptions"]["LengthFormat"] = Length::Architectural
    rescue StandardError
    end
    model.start_operation("Build MDL 9696 E", true)

    tag = lambda do |name, rgb|
      l = model.layers[name] || model.layers.add(name)
      (l.color = Sketchup::Color.new(*rgb)) rescue nil
      l
    end
    t_wall = tag.call("WR-Booth-Walls", [120, 128, 140])
    t_door = tag.call("WR-Booth-Door",  [238,  98,  22])
    t_vent = tag.call("WR-Booth-Vent",  [ 64, 102, 124])
    t_seal = tag.call("WR-Booth-Seals", [ 90,  90,  96])
    t_flr  = tag.call("WR-Booth-Floor", [210, 210, 210])

    booth = model.entities.add_group
    booth.name = "MDL 9696 E"

    f = booth.entities.add_group
    fc = f.entities.add_face([pt(0,0), pt(W,0), pt(W,H), pt(0,H)])
    fc.reverse! if fc && fc.normal.z < 0
    f.name = "floor"; f.layer = t_flr

    PARTS.each do |p|
      g = booth.entities.add_group
      face = g.entities.add_face([ pt(p[:x], p[:y]),
                                   pt(p[:x] + p[:dx], p[:y]),
                                   pt(p[:x] + p[:dx], p[:y] + p[:dy]),
                                   pt(p[:x], p[:y] + p[:dy]) ])
      next if face.nil?
      face.reverse! if face.normal.z < 0
      face.pushpull(PH)
      g.name  = p[:pack] ? "#{p[:id]}  #{p[:pack]}" : "#{p[:id]}  #{p[:sk]}"
      g.layer = if p[:k] == "seal" then t_seal
                elsif p[:sk] == "DRFRM" then t_door
                elsif p[:sk] == "VNT"   then t_vent
                else t_wall
                end
    end

    model.commit_operation
    model.active_view.zoom_extents

    puts ""
    puts "MDL 9696 E built."
    puts "  exterior 98.0\" x 98.0\"   interior 89.5\" x 89.5\""
    puts "  8 wall panels + 4 mid-wall seam seals, panels 1\" x 81\" tall"
    puts "  packing list lists 8 wall panels — agrees"
    puts "  NOTE: N wall [47, 47] -> [43.75, 43.75] (scaled), + 1 seal(s) = 89.50' run"
    puts "  NOTE: S wall [47, 47] -> [43.75, 43.75] (scaled), + 1 seal(s) = 89.50' run"
    puts "  NOTE: E wall [47, 47] -> [43.75, 43.75] (scaled), + 1 seal(s) = 89.50' run"
    puts "  NOTE: W wall [47, 47] -> [43.75, 43.75] (scaled), + 1 seal(s) = 89.50' run"
    puts "  Corner seam seals are NOT modelled yet — no dimensioned corner detail."
    puts ""
  rescue StandardError => e
    model.abort_operation if model
    puts "FAILED: #{e.class}: #{e.message}"
    puts e.backtrace.first(5)
  end
end

WR_BOOTH_9696_E.build
