# @title Build Booth MDL 96168 S
# @shelf archive
# GENERATED by scripts/gen-booth.py — regenerate, don't hand-edit.
#
# MDL 96168 S  ("Sound Booth · 8'×14'")
#   exterior  170.0" x 98.0"      interior 166.0" x 94.0"
#   panels    1" thick, 81" tall, separated by the 2" mid-wall seam-seal stem
#   run rule  interior = sum(panels) + 2" per joint
#
# Panel kinds are interchangeable — the door frame, vent, cable and window walls
# all swap into any position. What's drawn here is one arrangement, not a rule.

module WR_BOOTH_96168_S
  W = 170.0
  H = 98.0
  T = 2.0
  PH = 81.0

  PARTS = [
    { :k=>'panel', :id=>'N0', :sk=>'VNT', :poly=>[[2.0,96.0],[48.0,96.0],[48.0,97.0],[2.0,97.0]] },
    { :k=>'seal', :id=>'N-seal0', :sk=>'SEAL', :poly=>[[48.0,96.0],[50.0,96.0],[50.0,97.0],[52.875,97.0],[52.875,98.0],[45.125,98.0],[45.125,97.0],[48.0,97.0]] },
    { :k=>'panel', :id=>'N1', :sk=>'VNT', :poly=>[[50.0,96.0],[96.0,96.0],[96.0,97.0],[50.0,97.0]] },
    { :k=>'seal', :id=>'N-seal1', :sk=>'SEAL', :poly=>[[96.0,96.0],[98.0,96.0],[98.0,97.0],[100.875,97.0],[100.875,98.0],[93.125,98.0],[93.125,97.0],[96.0,97.0]] },
    { :k=>'panel', :id=>'N2', :sk=>'SOLID', :poly=>[[98.0,96.0],[120.0,96.0],[120.0,97.0],[98.0,97.0]] },
    { :k=>'seal', :id=>'N-seal2', :sk=>'SEAL', :poly=>[[120.0,96.0],[122.0,96.0],[122.0,97.0],[124.875,97.0],[124.875,98.0],[117.125,98.0],[117.125,97.0],[120.0,97.0]] },
    { :k=>'panel', :id=>'N3', :sk=>'VNT', :poly=>[[122.0,96.0],[168.0,96.0],[168.0,97.0],[122.0,97.0]] },
    { :k=>'panel', :id=>'S0', :sk=>'DRFRM', :poly=>[[2.0,1.0],[48.0,1.0],[48.0,2.0],[2.0,2.0]] },
    { :k=>'seal', :id=>'S-seal0', :sk=>'SEAL', :poly=>[[48.0,2.0],[48.0,1.0],[45.125,1.0],[45.125,0.0],[52.875,0.0],[52.875,1.0],[50.0,1.0],[50.0,2.0]] },
    { :k=>'panel', :id=>'S1', :sk=>'SOLID', :poly=>[[50.0,1.0],[96.0,1.0],[96.0,2.0],[50.0,2.0]] },
    { :k=>'seal', :id=>'S-seal1', :sk=>'SEAL', :poly=>[[96.0,2.0],[96.0,1.0],[93.125,1.0],[93.125,0.0],[100.875,0.0],[100.875,1.0],[98.0,1.0],[98.0,2.0]] },
    { :k=>'panel', :id=>'S2', :sk=>'SOLID', :poly=>[[98.0,1.0],[120.0,1.0],[120.0,2.0],[98.0,2.0]] },
    { :k=>'seal', :id=>'S-seal2', :sk=>'SEAL', :poly=>[[120.0,2.0],[120.0,1.0],[117.125,1.0],[117.125,0.0],[124.875,0.0],[124.875,1.0],[122.0,1.0],[122.0,2.0]] },
    { :k=>'panel', :id=>'S3', :sk=>'SOLID', :poly=>[[122.0,1.0],[168.0,1.0],[168.0,2.0],[122.0,2.0]] },
    { :k=>'panel', :id=>'E0', :sk=>'VNT', :poly=>[[168.0,2.0],[169.0,2.0],[169.0,48.0],[168.0,48.0]] },
    { :k=>'seal', :id=>'E-seal0', :sk=>'SEAL', :poly=>[[168.0,48.0],[169.0,48.0],[169.0,45.125],[170.0,45.125],[170.0,52.875],[169.0,52.875],[169.0,50.0],[168.0,50.0]] },
    { :k=>'panel', :id=>'E1', :sk=>'SOLID', :poly=>[[168.0,50.0],[169.0,50.0],[169.0,96.0],[168.0,96.0]] },
    { :k=>'panel', :id=>'W0', :sk=>'SOLID', :poly=>[[1.0,2.0],[2.0,2.0],[2.0,48.0],[1.0,48.0]] },
    { :k=>'seal', :id=>'W-seal0', :sk=>'SEAL', :poly=>[[2.0,48.0],[2.0,50.0],[1.0,50.0],[1.0,52.875],[0.0,52.875],[0.0,45.125],[1.0,45.125],[1.0,48.0]] },
    { :k=>'panel', :id=>'W1', :sk=>'SOLID', :poly=>[[1.0,50.0],[2.0,50.0],[2.0,96.0],[1.0,96.0]] },
    { :k=>'corner', :id=>'SW corner seal', :sk=>'CORNER', :poly=>[[0.0,0.0],[4.875,0.0],[4.875,1.0],[2.0,1.0],[2.0,2.0],[1.0,2.0],[1.0,4.875],[0.0,4.875]] },
    { :k=>'corner', :id=>'SE corner seal', :sk=>'CORNER', :poly=>[[170.0,0.0],[165.125,0.0],[165.125,1.0],[168.0,1.0],[168.0,2.0],[169.0,2.0],[169.0,4.875],[170.0,4.875]] },
    { :k=>'corner', :id=>'NW corner seal', :sk=>'CORNER', :poly=>[[0.0,98.0],[4.875,98.0],[4.875,97.0],[2.0,97.0],[2.0,96.0],[1.0,96.0],[1.0,93.125],[0.0,93.125]] },
    { :k=>'corner', :id=>'NE corner seal', :sk=>'CORNER', :poly=>[[170.0,98.0],[165.125,98.0],[165.125,97.0],[168.0,97.0],[168.0,96.0],[169.0,96.0],[169.0,93.125],[170.0,93.125]] }
  ]

  def self.pt(x, y, z = 0.0); Geom::Point3d.new(x, y, z); end

  def self.build
    model = Sketchup.active_model
    begin
      model.options["UnitsOptions"]["LengthFormat"] = Length::Architectural
    rescue StandardError
    end
    model.start_operation("Build MDL 96168 S", true)

    tag = lambda do |name, rgb|
      l = model.layers[name] || model.layers.add(name)
      (l.color = Sketchup::Color.new(*rgb)) rescue nil
      l
    end
    t_wall = tag.call("WR-Booth-Walls", [120, 128, 140])
    t_door = tag.call("WR-Booth-Door",  [238,  98,  22])
    t_vent = tag.call("WR-Booth-Vent",  [ 64, 102, 124])
    t_seal = tag.call("WR-Booth-Seals", [ 90,  90,  96])
    t_flr  = tag.call("WR-Booth-Floor", [210, 210, 210])

    booth = model.entities.add_group
    booth.name = "MDL 96168 S"

    f = booth.entities.add_group
    fc = f.entities.add_face([pt(0,0), pt(W,0), pt(W,H), pt(0,H)])
    fc.reverse! if fc && fc.normal.z < 0
    f.name = "floor"; f.layer = t_flr

    PARTS.each do |p|
      g = booth.entities.add_group
      face = g.entities.add_face([ pt(p[:x], p[:y]),
                                   pt(p[:x] + p[:dx], p[:y]),
                                   pt(p[:x] + p[:dx], p[:y] + p[:dy]),
                                   pt(p[:x], p[:y] + p[:dy]) ])
      next if face.nil?
      face.reverse! if face.normal.z < 0
      face.pushpull(PH)
      g.name  = p[:pack] ? "#{p[:id]}  #{p[:pack]}" : "#{p[:id]}  #{p[:sk]}"
      g.layer = if p[:k] == "seal" then t_seal
                elsif p[:sk] == "DRFRM" then t_door
                elsif p[:sk] == "VNT"   then t_vent
                else t_wall
                end
    end

    model.commit_operation
    model.active_view.zoom_extents

    puts ""
    puts "MDL 96168 S built."
    puts "  exterior 170.0\" x 98.0\"   interior 166.0\" x 94.0\""
    puts "  12 wall panels + 8 mid-wall seam seals, panels 1\" x 81\" tall"
    puts "  packing list lists 12 wall panels — agrees"
    puts "  NOTE: E wall [47, 47] -> [46, 46] (solved from stock), + 1 seal(s) = 94.00' run"
    puts "  NOTE: W wall [47, 47] -> [46, 46] (solved from stock), + 1 seal(s) = 94.00' run"
    puts "  Corner seam seals are NOT modelled yet — no dimensioned corner detail."
    puts ""
  rescue StandardError => e
    model.abort_operation if model
    puts "FAILED: #{e.class}: #{e.message}"
    puts e.backtrace.first(5)
  end
end

WR_BOOTH_96168_S.build
